/*******************************************************************************
** cart.h (carts & patches)
*******************************************************************************/

#ifndef CART_H
#define CART_H

#include "bank.h"

enum
{
  PATCH_ALGORITHM_VAL_1C_CHAIN = 0, 
  PATCH_ALGORITHM_VAL_1C_THE_Y, 
  PATCH_ALGORITHM_VAL_1C_CRAB_CLAW, 
  PATCH_ALGORITHM_VAL_2C_STACKED, 
  PATCH_ALGORITHM_VAL_2C_TWIN, 
  PATCH_ALGORITHM_VAL_3C_1_TO_1, 
  PATCH_ALGORITHM_VAL_3C_1_TO_3, 
  PATCH_ALGORITHM_VAL_4C_PIPES, 
  PATCH_NUM_ALGORITHM_VALS 
};

enum
{
  PATCH_WAVEFORM_VAL_SINE = 0, 
  PATCH_WAVEFORM_VAL_HALF, 
  PATCH_WAVEFORM_VAL_FULL, 
  PATCH_WAVEFORM_VAL_QUARTER, 
  PATCH_NUM_WAVEFORM_VALS 
};

enum
{
  PATCH_FREQ_MODE_VAL_SINE = 0, 
  PATCH_FREQ_MODE_VAL_HALF, 
  PATCH_FREQ_MODE_VAL_FULL, 
  PATCH_FREQ_MODE_VAL_QUARTER, 
  PATCH_NUM_FREQ_MODE_VALS 
};

enum
{
  PATCH_PARAM_ALGORITHM = 0, 
  PATCH_PARAM_LEGACY_KEYSCALE, 
  PATCH_PARAM_NOISE_ENABLE, 
  /* osc sync */
  PATCH_PARAM_OSC_SYNC, 
  /* osc 1 */
  PATCH_PARAM_OSC_1_WAVEFORM, 
  PATCH_PARAM_OSC_1_FEEDBACK, 
  PATCH_PARAM_OSC_1_PHI, 
  PATCH_PARAM_OSC_1_FREQ_MODE, 
  PATCH_PARAM_OSC_1_MULTIPLE, 
  PATCH_PARAM_OSC_1_DIVISOR, 
  PATCH_PARAM_OSC_1_DETUNE, 
  /* osc 2 */
  PATCH_PARAM_OSC_2_WAVEFORM, 
  PATCH_PARAM_OSC_2_FEEDBACK, 
  PATCH_PARAM_OSC_2_PHI, 
  PATCH_PARAM_OSC_2_FREQ_MODE, 
  PATCH_PARAM_OSC_2_MULTIPLE, 
  PATCH_PARAM_OSC_2_DIVISOR, 
  PATCH_PARAM_OSC_2_DETUNE, 
  /* osc 3 */
  PATCH_PARAM_OSC_3_WAVEFORM, 
  PATCH_PARAM_OSC_3_FEEDBACK, 
  PATCH_PARAM_OSC_3_PHI, 
  PATCH_PARAM_OSC_3_FREQ_MODE, 
  PATCH_PARAM_OSC_3_MULTIPLE, 
  PATCH_PARAM_OSC_3_DIVISOR, 
  PATCH_PARAM_OSC_3_DETUNE, 
  /* osc 4 */
  PATCH_PARAM_OSC_4_WAVEFORM, 
  PATCH_PARAM_OSC_4_FEEDBACK, 
  PATCH_PARAM_OSC_4_PHI, 
  PATCH_PARAM_OSC_4_FREQ_MODE, 
  PATCH_PARAM_OSC_4_MULTIPLE, 
  PATCH_PARAM_OSC_4_DIVISOR, 
  PATCH_PARAM_OSC_4_DETUNE, 
  /* env 1 */
  PATCH_PARAM_ENV_1_ATTACK, 
  PATCH_PARAM_ENV_1_DECAY, 
  PATCH_PARAM_ENV_1_SUSTAIN, 
  PATCH_PARAM_ENV_1_RELEASE, 
  PATCH_PARAM_ENV_1_MAX_LEVEL, 
  PATCH_PARAM_ENV_1_HOLD_MODE, 
  PATCH_PARAM_ENV_1_HOLD_LEVEL, 
  PATCH_PARAM_ENV_1_RATE_KEYSCALING, 
  PATCH_PARAM_ENV_1_LEVEL_KEYSCALING, 
  /* env 2 */
  PATCH_PARAM_ENV_2_ATTACK, 
  PATCH_PARAM_ENV_2_DECAY, 
  PATCH_PARAM_ENV_2_SUSTAIN, 
  PATCH_PARAM_ENV_2_RELEASE, 
  PATCH_PARAM_ENV_2_MAX_LEVEL, 
  PATCH_PARAM_ENV_2_HOLD_MODE, 
  PATCH_PARAM_ENV_2_HOLD_LEVEL, 
  PATCH_PARAM_ENV_2_RATE_KEYSCALING, 
  PATCH_PARAM_ENV_2_LEVEL_KEYSCALING, 
  /* env 3 */
  PATCH_PARAM_ENV_3_ATTACK, 
  PATCH_PARAM_ENV_3_DECAY, 
  PATCH_PARAM_ENV_3_SUSTAIN, 
  PATCH_PARAM_ENV_3_RELEASE, 
  PATCH_PARAM_ENV_3_MAX_LEVEL, 
  PATCH_PARAM_ENV_3_HOLD_MODE, 
  PATCH_PARAM_ENV_3_HOLD_LEVEL, 
  PATCH_PARAM_ENV_3_RATE_KEYSCALING, 
  PATCH_PARAM_ENV_3_LEVEL_KEYSCALING, 
  /* env 4 */
  PATCH_PARAM_ENV_4_ATTACK, 
  PATCH_PARAM_ENV_4_DECAY, 
  PATCH_PARAM_ENV_4_SUSTAIN, 
  PATCH_PARAM_ENV_4_RELEASE, 
  PATCH_PARAM_ENV_4_MAX_LEVEL, 
  PATCH_PARAM_ENV_4_HOLD_MODE, 
  PATCH_PARAM_ENV_4_HOLD_LEVEL, 
  PATCH_PARAM_ENV_4_RATE_KEYSCALING, 
  PATCH_PARAM_ENV_4_LEVEL_KEYSCALING, 
  /* effect routing */
  PATCH_PARAM_VIBRATO_ROUTING_OSC_1, 
  PATCH_PARAM_VIBRATO_ROUTING_OSC_2, 
  PATCH_PARAM_VIBRATO_ROUTING_OSC_3, 
  PATCH_PARAM_VIBRATO_ROUTING_OSC_4, 
  PATCH_PARAM_TREMOLO_ROUTING_ENV_1, 
  PATCH_PARAM_TREMOLO_ROUTING_ENV_2, 
  PATCH_PARAM_TREMOLO_ROUTING_ENV_3, 
  PATCH_PARAM_TREMOLO_ROUTING_ENV_4, 
  PATCH_PARAM_BOOST_ROUTING_ENV_1, 
  PATCH_PARAM_BOOST_ROUTING_ENV_2, 
  PATCH_PARAM_BOOST_ROUTING_ENV_3, 
  PATCH_PARAM_BOOST_ROUTING_ENV_4, 
  PATCH_PARAM_VELOCITY_ROUTING_ENV_1, 
  PATCH_PARAM_VELOCITY_ROUTING_ENV_2, 
  PATCH_PARAM_VELOCITY_ROUTING_ENV_3, 
  PATCH_PARAM_VELOCITY_ROUTING_ENV_4, 
  /* vibrato */
  PATCH_PARAM_VIBRATO_WAVEFORM, 
  PATCH_PARAM_VIBRATO_DELAY, 
  PATCH_PARAM_VIBRATO_SPEED, 
  PATCH_PARAM_VIBRATO_DEPTH, 
  PATCH_PARAM_VIBRATO_SENSITIVITY, 
  PATCH_PARAM_VIBRATO_SYNC, 
  /* tremolo */
  PATCH_PARAM_TREMOLO_WAVEFORM, 
  PATCH_PARAM_TREMOLO_DELAY, 
  PATCH_PARAM_TREMOLO_SPEED, 
  PATCH_PARAM_TREMOLO_DEPTH, 
  PATCH_PARAM_TREMOLO_SENSITIVITY, 
  PATCH_PARAM_TREMOLO_SYNC, 
  /* boost, velocity */
  PATCH_PARAM_BOOST_SENSITIVITY, 
  PATCH_PARAM_VELOCITY_SENSITIVITY, 
  /* pitch envelope */
  PATCH_PARAM_PITCH_ENV_ATTACK, 
  PATCH_PARAM_PITCH_ENV_DECAY, 
  PATCH_PARAM_PITCH_ENV_RELEASE, 
  PATCH_PARAM_PITCH_ENV_MAX, 
  PATCH_PARAM_PITCH_ENV_FINALE, 
  /* filters */
  PATCH_PARAM_HIGHPASS_CUTOFF, 
  PATCH_PARAM_LOWPASS_CUTOFF, 
  /* pitch wheel */
  PATCH_PARAM_PITCH_WHEEL_MODE, 
  PATCH_PARAM_PITCH_WHEEL_RANGE, 
  /* arpeggio */
  PATCH_PARAM_ARPEGGIO_MODE, 
  PATCH_PARAM_ARPEGGIO_PATTERN, 
  PATCH_PARAM_ARPEGGIO_OCTAVE, 
  PATCH_PARAM_ARPEGGIO_SPEED, 
  /* portamento */
  PATCH_PARAM_PORTAMENTO_MODE, 
  PATCH_PARAM_PORTAMENTO_LEGATO, 
  PATCH_PARAM_PORTAMENTO_SPEED, 
  /* midi controller routing */
  PATCH_PARAM_MOD_WHEEL_ROUTING_VIBRATO, 
  PATCH_PARAM_MOD_WHEEL_ROUTING_TREMOLO, 
  PATCH_PARAM_MOD_WHEEL_ROUTING_BOOST, 
  PATCH_PARAM_AFTERTOUCH_ROUTING_VIBRATO, 
  PATCH_PARAM_AFTERTOUCH_ROUTING_TREMOLO, 
  PATCH_PARAM_AFTERTOUCH_ROUTING_BOOST, 
  PATCH_PARAM_EXP_PEDAL_ROUTING_VIBRATO, 
  PATCH_PARAM_EXP_PEDAL_ROUTING_TREMOLO, 
  PATCH_PARAM_EXP_PEDAL_ROUTING_BOOST, 
  PATCH_NUM_PARAMS
};

/* name strings: 12 characters + 1 null terminator */
#define CART_NAME_SIZE  (12 + 1)
#define PATCH_NAME_SIZE (12 + 1)

#define CART_CHARACTER_IS_VALID_IN_CART_OR_PATCH_NAME(c)                       \
  ( (c == ' ')                  ||                                             \
    (c == '\0')                 ||                                             \
    ((c >= '0') && (c <= '9'))  ||                                             \
    ((c >= 'A') && (c <= 'Z'))  ||                                             \
    ((c >= 'a') && (c <= 'z')))

/* compute oscillator and envelope shifted parameter indices */
#define PATCH_PARAM_COMPUTE_OSC_INDEX(name, num)                               \
  (PATCH_PARAM_OSC_1_##name + ((num) - 1) * (PATCH_PARAM_OSC_2_WAVEFORM - PATCH_PARAM_OSC_1_WAVEFORM))

#define PATCH_PARAM_COMPUTE_ENV_INDEX(name, num)                               \
  (PATCH_PARAM_ENV_1_##name + ((num) - 1) * (PATCH_PARAM_ENV_2_ATTACK - PATCH_PARAM_ENV_1_ATTACK))

/* check if a parameter is within bounds */
#define PATCH_PARAM_IS_VALID_LOOKUP_BY_INDEX(index)                            \
  ( (p->values[index] >= 0) &&                                                 \
    (p->values[index] <= G_patch_param_bounds[index]))

#define PATCH_PARAM_IS_NOT_VALID_LOOKUP_BY_INDEX(index)                        \
  (!(PATCH_PARAM_IS_VALID_LOOKUP_BY_INDEX(index)))

#define PATCH_PARAM_IS_VALID_LOOKUP_BY_NAME(name)                              \
  ( (p->values[PATCH_PARAM_##name] >= 0) &&                                    \
    (p->values[PATCH_PARAM_##name] <= G_patch_param_bounds[PATCH_PARAM_##name]))

#define PATCH_PARAM_IS_NOT_VALID_LOOKUP_BY_NAME(name)                          \
  (!(PATCH_PARAM_IS_VALID_LOOKUP_BY_NAME(name)))

#define PATCH_PARAM_IS_VALID_LOOKUP_OSC_PARAM(name, num)                       \
  PATCH_PARAM_IS_VALID_LOOKUP_BY_INDEX(PATCH_PARAM_COMPUTE_OSC_INDEX(name, num))

#define PATCH_PARAM_IS_VALID_LOOKUP_ENV_PARAM(name, num)                       \
  PATCH_PARAM_IS_VALID_LOOKUP_BY_INDEX(PATCH_PARAM_COMPUTE_ENV_INDEX(name, num))

#define PATCH_VALUE_IS_VALID_LOOKUP_BY_NAME(val, name)                         \
  ((val >= 0) && (val <= G_patch_param_bounds[PATCH_PARAM_##name]))

#define PATCH_VALUE_IS_NOT_VALID_LOOKUP_BY_NAME(val, name)                     \
  (!(PATCH_VALUE_IS_VALID_LOOKUP_BY_NAME(val, name)))

/* cart parameters */
#define PATCH_CART_NUMBER_DEFAULT       1
#define PATCH_CART_NUMBER_LOWER_BOUND   1
#define PATCH_CART_NUMBER_UPPER_BOUND   BANK_NUM_CARTS
#define PATCH_CART_NUMBER_NUM_VALUES    (PATCH_CART_NUMBER_UPPER_BOUND - PATCH_CART_NUMBER_LOWER_BOUND + 1)

#define PATCH_PATCH_NUMBER_DEFAULT      1
#define PATCH_PATCH_NUMBER_LOWER_BOUND  1
#define PATCH_PATCH_NUMBER_UPPER_BOUND  BANK_PATCHES_PER_CART
#define PATCH_PATCH_NUMBER_NUM_VALUES   (PATCH_PATCH_NUMBER_UPPER_BOUND - PATCH_PATCH_NUMBER_LOWER_BOUND + 1)

typedef struct patch
{
  char name[PATCH_NAME_SIZE];

  unsigned char values[PATCH_NUM_PARAMS];
} patch;

typedef struct cart
{
  char name[CART_NAME_SIZE];

  patch patches[BANK_PATCHES_PER_CART];
} cart;

/* cart bank */
extern cart G_cart_bank[BANK_NUM_CARTS];

/* patch parameter bounds array */
extern unsigned char G_patch_param_bounds[PATCH_NUM_PARAMS];

/* function declarations */
short int cart_reset_all();

short int cart_reset_patch(int cart_index, int patch_index);
short int cart_validate_patch(int cart_index, int patch_index);
short int cart_copy_patch(int dest_cart_index,  int dest_patch_index, 
                          int src_cart_index,   int src_patch_index);

short int cart_reset_cart(int cart_index);
short int cart_validate_cart(int cart_index);
short int cart_copy_cart(int dest_cart_index, int src_cart_index);

#endif
