/*******************************************************************************
** import.h (loading non-native file formats)
*******************************************************************************/

#ifndef IMPORT_H
#define IMPORT_H

enum
{ IMPORT_BATCHING_1 = 1, 
  IMPORT_BATCHING_8, 
  IMPORT_BATCHING_16 
};

#define IMPORT_INSTRUMENT_ID_IS_VALID(id)                                      \
  ((id >= 0) && (id < num_patches))

#define IMPORT_INSTRUMENT_ID_IS_NOT_VALID(id)                                  \
  (!(IMPORT_INSTRUMENT_ID_IS_VALID(id)))

/* opl patches: ym3812 (adlib), ymf262 (soundblaster) */
#define IMPORT_OPL_ALGORITHM_NUM_VALUES       4
#define IMPORT_OPL_FEEDBACK_NUM_VALUES        8
#define IMPORT_OPL_VIBRATO_DEPTH_NUM_VALUES   2
#define IMPORT_OPL_TREMOLO_DEPTH_NUM_VALUES   2

#define IMPORT_OPL_MULTIPLE_NUM_VALUES       16
#define IMPORT_OPL_WAVEFORM_NUM_VALUES        8
#define IMPORT_OPL_ENV_RATE_NUM_VALUES       16
#define IMPORT_OPL_TOTAL_LEVEL_NUM_VALUES    64
#define IMPORT_OPL_SUSTAIN_LEVEL_NUM_VALUES  16
#define IMPORT_OPL_RATE_KEYSCALE_NUM_VALUES   2
#define IMPORT_OPL_LEVEL_KEYSCALE_NUM_VALUES  4

#define IMPORT_OPL_SUSTAIN_ENABLE_NUM_VALUES  2
#define IMPORT_OPL_VIBRATO_ENABLE_NUM_VALUES  2
#define IMPORT_OPL_TREMOLO_ENABLE_NUM_VALUES  2

/* opn patches: ym2612 (genesis), ym2610 (neo geo), ym2608 (pc-98) */
#define IMPORT_YM2612_ALGORITHM_NUM_VALUES        8
#define IMPORT_YM2612_FEEDBACK_NUM_VALUES         8
#define IMPORT_YM2612_VIBRATO_DEPTH_NUM_VALUES    8
#define IMPORT_YM2612_TREMOLO_DEPTH_NUM_VALUES    4

#define IMPORT_YM2612_MULTIPLE_NUM_VALUES        16
#define IMPORT_YM2612_DETUNE_NUM_VALUES           8
#define IMPORT_YM2612_ENV_RATE_NUM_VALUES        32
#define IMPORT_YM2612_TOTAL_LEVEL_NUM_VALUES    128
#define IMPORT_YM2612_SUSTAIN_LEVEL_NUM_VALUES   16
#define IMPORT_YM2612_RATE_KEYSCALE_NUM_VALUES    4

/* opm patches: ym2151 (sharp x68k, various arcade games) */
#define IMPORT_YM2151_ALGORITHM_NUM_VALUES          8
#define IMPORT_YM2151_FEEDBACK_NUM_VALUES           8
#define IMPORT_YM2151_VIBRATO_DEPTH_NUM_VALUES      8
#define IMPORT_YM2151_TREMOLO_DEPTH_NUM_VALUES      4
#define IMPORT_YM2151_NOISE_ENABLE_NUM_VALUES       2
#define IMPORT_YM2151_NOISE_FREQUENCY_NUM_VALUES   32
#define IMPORT_YM2151_LFO_FREQUENCY_NUM_VALUES    256
#define IMPORT_YM2151_LFO_WAVEFORM_NUM_VALUES       4
#define IMPORT_YM2151_EFFECT_BASE_NUM_VALUES      128
#define IMPORT_YM2151_EFFECT_BASE_DIVISOR           4

#define IMPORT_YM2151_MULTIPLE_NUM_VALUES          16
#define IMPORT_YM2151_DETUNE_1_NUM_VALUES           8
#define IMPORT_YM2151_DETUNE_2_NUM_VALUES           4
#define IMPORT_YM2151_ENV_RATE_NUM_VALUES          32
#define IMPORT_YM2151_TOTAL_LEVEL_NUM_VALUES      128
#define IMPORT_YM2151_SUSTAIN_LEVEL_NUM_VALUES     16
#define IMPORT_YM2151_RATE_KEYSCALE_NUM_VALUES      4

/* sbi format (.sbi, .sb, .03) for opl patches */
enum
{
  IMPORT_SBI_SHARED_BYTE_MODULATOR_MULTIPLE_FLAGS = 0, 
  IMPORT_SBI_SHARED_BYTE_CARRIER_MULTIPLE_FLAGS, 
  IMPORT_SBI_SHARED_BYTE_MODULATOR_LEVEL_KEYSCALE_TOTAL_LEVEL, 
  IMPORT_SBI_SHARED_BYTE_CARRIER_LEVEL_KEYSCALE_TOTAL_LEVEL, 
  IMPORT_SBI_SHARED_BYTE_MODULATOR_ATTACK_RATE_DECAY_RATE, 
  IMPORT_SBI_SHARED_BYTE_CARRIER_ATTACK_RATE_DECAY_RATE, 
  IMPORT_SBI_SHARED_BYTE_MODULATOR_SUSTAIN_LEVEL_RELEASE_RATE, 
  IMPORT_SBI_SHARED_BYTE_CARRIER_SUSTAIN_LEVEL_RELEASE_RATE, 
  IMPORT_SBI_SHARED_BYTE_MODULATOR_WAVEFORM, 
  IMPORT_SBI_SHARED_BYTE_CARRIER_WAVEFORM, 
  IMPORT_SBI_SHARED_BYTE_FEEDBACK_ALGORITHM, 
  IMPORT_SBI_SHARED_NUM_BYTES 
};

enum
{
  IMPORT_SBI_2OP_EXTRA_BYTE_RESERVED_1 = 0, 
  IMPORT_SBI_2OP_EXTRA_BYTE_RESERVED_2, 
  IMPORT_SBI_2OP_EXTRA_BYTE_RESERVED_3, 
  IMPORT_SBI_2OP_EXTRA_BYTE_RESERVED_4, 
  IMPORT_SBI_2OP_EXTRA_BYTE_RESERVED_5, 
  IMPORT_SBI_2OP_EXTRA_NUM_BYTES 
};

enum
{
  IMPORT_SBI_4OP_EXTRA_BYTE_MODULATOR_MULTIPLE_FLAGS = 0, 
  IMPORT_SBI_4OP_EXTRA_BYTE_CARRIER_MULTIPLE_FLAGS, 
  IMPORT_SBI_4OP_EXTRA_BYTE_MODULATOR_LEVEL_KEYSCALE_TOTAL_LEVEL, 
  IMPORT_SBI_4OP_EXTRA_BYTE_CARRIER_LEVEL_KEYSCALE_TOTAL_LEVEL, 
  IMPORT_SBI_4OP_EXTRA_BYTE_MODULATOR_ATTACK_RATE_DECAY_RATE, 
  IMPORT_SBI_4OP_EXTRA_BYTE_CARRIER_ATTACK_RATE_DECAY_RATE, 
  IMPORT_SBI_4OP_EXTRA_BYTE_MODULATOR_SUSTAIN_LEVEL_RELEASE_RATE, 
  IMPORT_SBI_4OP_EXTRA_BYTE_CARRIER_SUSTAIN_LEVEL_RELEASE_RATE, 
  IMPORT_SBI_4OP_EXTRA_BYTE_MODULATOR_WAVEFORM, 
  IMPORT_SBI_4OP_EXTRA_BYTE_CARRIER_WAVEFORM, 
  IMPORT_SBI_4OP_EXTRA_BYTE_ALGORITHM, 
  IMPORT_SBI_4OP_EXTRA_BYTE_RESERVED_1, 
  IMPORT_SBI_4OP_EXTRA_BYTE_RESERVED_2, 
  IMPORT_SBI_4OP_EXTRA_NUM_BYTES 
};

enum
{
  IMPORT_SBI_TYPE_SBI = 0, 
  IMPORT_SBI_TYPE_2OP, 
  IMPORT_SBI_TYPE_4OP 
};

/* the 2-op file should be 16 bytes (52 when including the magic number & patch name) */
/* the 4-op file should be 24 bytes (60 when including the magic number & patch name) */
#define IMPORT_SBI_PATCH_NAME_NUM_BYTES 32

#define IMPORT_SBI_2OP_TOTAL_NUM_BYTES  ( IMPORT_SBI_SHARED_NUM_BYTES +        \
                                          IMPORT_SBI_2OP_EXTRA_NUM_BYTES)

#define IMPORT_SBI_4OP_TOTAL_NUM_BYTES  ( IMPORT_SBI_SHARED_NUM_BYTES +        \
                                          IMPORT_SBI_4OP_EXTRA_NUM_BYTES)

#define IMPORT_SBI_SHARED_START_INDEX 0
#define IMPORT_SBI_SHARED_END_INDEX   ( IMPORT_SBI_SHARED_START_INDEX +        \
                                        IMPORT_SBI_SHARED_NUM_BYTES)

#define IMPORT_SBI_2OP_EXTRA_START_INDEX  IMPORT_SBI_SHARED_END_INDEX
#define IMPORT_SBI_2OP_EXTRA_END_INDEX    ( IMPORT_SBI_2OP_EXTRA_START_INDEX + \
                                            IMPORT_SBI_2OP_EXTRA_NUM_BYTES)

#define IMPORT_SBI_4OP_EXTRA_START_INDEX  IMPORT_SBI_SHARED_END_INDEX
#define IMPORT_SBI_4OP_EXTRA_END_INDEX    ( IMPORT_SBI_4OP_EXTRA_START_INDEX + \
                                            IMPORT_SBI_4OP_EXTRA_NUM_BYTES)

#define IMPORT_SBI_MAX_PATCHES 128

#define IMPORT_SBI_M1_START_INDEX                                              \
  (IMPORT_SBI_SHARED_START_INDEX + IMPORT_SBI_SHARED_BYTE_MODULATOR_MULTIPLE_FLAGS)

#define IMPORT_SBI_C1_START_INDEX                                              \
  (IMPORT_SBI_SHARED_START_INDEX + IMPORT_SBI_SHARED_BYTE_CARRIER_MULTIPLE_FLAGS)

#define IMPORT_SBI_M2_START_INDEX                                              \
  (IMPORT_SBI_4OP_EXTRA_START_INDEX + IMPORT_SBI_4OP_EXTRA_BYTE_MODULATOR_MULTIPLE_FLAGS)

#define IMPORT_SBI_C2_START_INDEX                                              \
  (IMPORT_SBI_4OP_EXTRA_START_INDEX + IMPORT_SBI_4OP_EXTRA_BYTE_CARRIER_MULTIPLE_FLAGS)

#define IMPORT_SBI_OPERATOR_OFFSET_MULTIPLE_FLAGS                              \
  (IMPORT_SBI_SHARED_BYTE_MODULATOR_MULTIPLE_FLAGS - IMPORT_SBI_M1_START_INDEX)

#define IMPORT_SBI_OPERATOR_OFFSET_LEVEL_KEYSCALE_TOTAL_LEVEL                  \
  (IMPORT_SBI_SHARED_BYTE_MODULATOR_LEVEL_KEYSCALE_TOTAL_LEVEL - IMPORT_SBI_M1_START_INDEX)

#define IMPORT_SBI_OPERATOR_OFFSET_ATTACK_RATE_DECAY_RATE                      \
  (IMPORT_SBI_SHARED_BYTE_MODULATOR_ATTACK_RATE_DECAY_RATE - IMPORT_SBI_M1_START_INDEX)

#define IMPORT_SBI_OPERATOR_OFFSET_SUSTAIN_LEVEL_RELEASE_RATE                  \
  (IMPORT_SBI_SHARED_BYTE_MODULATOR_SUSTAIN_LEVEL_RELEASE_RATE - IMPORT_SBI_M1_START_INDEX)

#define IMPORT_SBI_OPERATOR_OFFSET_WAVEFORM                                    \
  (IMPORT_SBI_SHARED_BYTE_MODULATOR_WAVEFORM - IMPORT_SBI_M1_START_INDEX)

#define IMPORT_SBI_COMPUTE_BYTE_SHARED_INDEX(name)                             \
  ( IMPORT_SBI_SHARED_START_INDEX +                                            \
    IMPORT_SBI_SHARED_BYTE_##name)

#define IMPORT_SBI_COMPUTE_BYTE_2OP_EXTRA_INDEX(name)                          \
  ( IMPORT_SBI_2OP_EXTRA_START_INDEX +                                         \
    IMPORT_SBI_2OP_EXTRA_BYTE_##name)

#define IMPORT_SBI_COMPUTE_BYTE_4OP_EXTRA_INDEX(name)                          \
  ( IMPORT_SBI_4OP_EXTRA_START_INDEX +                                         \
    IMPORT_SBI_4OP_EXTRA_BYTE_##name)

/* tfi format (.tfi) for opn patches */
enum
{
  IMPORT_TFI_BYTE_GENERAL_ALGORITHM = 0, 
  IMPORT_TFI_BYTE_GENERAL_FEEDBACK, 
  IMPORT_TFI_NUM_GENERAL_BYTES 
};

enum
{
  IMPORT_TFI_BYTE_OPERATOR_MULTIPLE = 0, 
  IMPORT_TFI_BYTE_OPERATOR_DETUNE, 
  IMPORT_TFI_BYTE_OPERATOR_TOTAL_LEVEL, 
  IMPORT_TFI_BYTE_OPERATOR_RATE_KEYSCALE, 
  IMPORT_TFI_BYTE_OPERATOR_ATTACK_RATE, 
  IMPORT_TFI_BYTE_OPERATOR_DECAY_1_RATE, 
  IMPORT_TFI_BYTE_OPERATOR_DECAY_2_RATE, 
  IMPORT_TFI_BYTE_OPERATOR_RELEASE_RATE, 
  IMPORT_TFI_BYTE_OPERATOR_SUSTAIN_LEVEL, 
  IMPORT_TFI_BYTE_OPERATOR_SSG_EG, 
  IMPORT_TFI_NUM_OPERATOR_BYTES 
};

/* the .tfi file should be 42 bytes */
#define IMPORT_TFI_NUM_BYTES  ( IMPORT_TFI_NUM_GENERAL_BYTES +                 \
                                (4 * IMPORT_TFI_NUM_OPERATOR_BYTES))

#define IMPORT_TFI_GENERAL_START_INDEX  0
#define IMPORT_TFI_GENERAL_END_INDEX    ( IMPORT_TFI_GENERAL_START_INDEX +     \
                                          IMPORT_TFI_NUM_GENERAL_BYTES)

#define IMPORT_TFI_OPERATOR_START_INDEX   IMPORT_TFI_GENERAL_END_INDEX
#define IMPORT_TFI_OPERATOR_END_INDEX     ( IMPORT_TFI_OPERATOR_START_INDEX +  \
                                            4 * IMPORT_TFI_NUM_OPERATOR_BYTES)

#define IMPORT_TFI_MAX_PATCHES 128

#define IMPORT_TFI_COMPUTE_BYTE_GENERAL_INDEX(name)                            \
  ( IMPORT_TFI_GENERAL_START_INDEX +                                           \
    IMPORT_TFI_BYTE_GENERAL_##name)

#define IMPORT_TFI_COMPUTE_BYTE_OPERATOR_INDEX(op_num, name)                   \
  ( IMPORT_TFI_OPERATOR_START_INDEX +                                          \
    (op_num * IMPORT_TFI_NUM_OPERATOR_BYTES) +                                 \
    IMPORT_TFI_BYTE_OPERATOR_##name)

/* opm format (.opm) for opm patches */
enum
{
  IMPORT_OPM_VALUE_GENERAL_LFO_FREQUENCY = 0, /* LFO label */
  IMPORT_OPM_VALUE_GENERAL_TREMOLO_BASE, 
  IMPORT_OPM_VALUE_GENERAL_VIBRATO_BASE, 
  IMPORT_OPM_VALUE_GENERAL_LFO_WAVEFORM, 
  IMPORT_OPM_VALUE_GENERAL_NOISE_FREQUENCY, 
  IMPORT_OPM_VALUE_GENERAL_PANNING,           /* CH label */
  IMPORT_OPM_VALUE_GENERAL_FEEDBACK, 
  IMPORT_OPM_VALUE_GENERAL_ALGORITHM, 
  IMPORT_OPM_VALUE_GENERAL_TREMOLO_DEPTH, 
  IMPORT_OPM_VALUE_GENERAL_VIBRATO_DEPTH, 
  IMPORT_OPM_VALUE_GENERAL_SLOT_MASK, 
  IMPORT_OPM_VALUE_GENERAL_NOISE_ENABLE, 
  IMPORT_OPM_NUM_GENERAL_VALUES 
};

enum
{
  IMPORT_OPM_VALUE_OPERATOR_ATTACK_RATE = 0, /* M1, C1, M2, C2 labels */
  IMPORT_OPM_VALUE_OPERATOR_DECAY_1_RATE, 
  IMPORT_OPM_VALUE_OPERATOR_DECAY_2_RATE, 
  IMPORT_OPM_VALUE_OPERATOR_RELEASE_RATE, 
  IMPORT_OPM_VALUE_OPERATOR_SUSTAIN_LEVEL, 
  IMPORT_OPM_VALUE_OPERATOR_TOTAL_LEVEL, 
  IMPORT_OPM_VALUE_OPERATOR_RATE_KEYSCALE, 
  IMPORT_OPM_VALUE_OPERATOR_MULTIPLE, 
  IMPORT_OPM_VALUE_OPERATOR_DETUNE_1, 
  IMPORT_OPM_VALUE_OPERATOR_DETUNE_2, 
  IMPORT_OPM_VALUE_OPERATOR_TREMOLO_ENABLE, 
  IMPORT_OPM_NUM_OPERATOR_VALUES 
};

#define IMPORT_OPM_TEXT_LINE_MAX_LENGTH   256

#define IMPORT_OPM_NUM_VALUES ( IMPORT_OPM_NUM_GENERAL_VALUES +                \
                                (4 * IMPORT_OPM_NUM_OPERATOR_VALUES))

#define IMPORT_OPM_GENERAL_START_INDEX  0
#define IMPORT_OPM_GENERAL_END_INDEX    ( IMPORT_OPM_GENERAL_START_INDEX +     \
                                          IMPORT_OPM_NUM_GENERAL_VALUES)

#define IMPORT_OPM_OPERATOR_START_INDEX   IMPORT_OPM_GENERAL_END_INDEX
#define IMPORT_OPM_OPERATOR_END_INDEX     ( IMPORT_OPM_OPERATOR_START_INDEX +  \
                                            4 * IMPORT_OPM_NUM_OPERATOR_VALUES)

#define IMPORT_OPM_MAX_PATCHES 128

#define IMPORT_OPM_COMPUTE_VALUE_GENERAL_INDEX(name)                           \
  ( IMPORT_OPM_GENERAL_START_INDEX +                                           \
    IMPORT_OPM_VALUE_GENERAL_##name)

#define IMPORT_OPM_COMPUTE_VALUE_OPERATOR_INDEX(op_num, name)                  \
  ( IMPORT_OPM_OPERATOR_START_INDEX +                                          \
    (op_num * IMPORT_OPM_NUM_OPERATOR_VALUES) +                                \
    IMPORT_OPM_VALUE_OPERATOR_##name)

/* function declarations */
short int import_sbi_load(int cart_num, int patch_num, 
                          char* filename, int inst_id, int batching);
short int import_tfi_load(int cart_num, int patch_num, 
                          char* filename, int inst_id, int batching);
short int import_opm_load(int cart_num, int patch_num, 
                          char* filename, int inst_id, int batching);

#endif
