/*******************************************************************************
** key.h (musical keys)
*******************************************************************************/

#ifndef KEY_H
#define KEY_H

#if 0
enum
{
  /* major keys */
  KEY_SIGNATURE_C_FLAT_MAJOR = 0, /* 7 flats  */
  KEY_SIGNATURE_G_FLAT_MAJOR,
  KEY_SIGNATURE_D_FLAT_MAJOR,
  KEY_SIGNATURE_A_FLAT_MAJOR,
  KEY_SIGNATURE_E_FLAT_MAJOR,
  KEY_SIGNATURE_B_FLAT_MAJOR,
  KEY_SIGNATURE_F_MAJOR,
  KEY_SIGNATURE_C_MAJOR,          /* clear    */
  KEY_SIGNATURE_G_MAJOR,
  KEY_SIGNATURE_D_MAJOR,
  KEY_SIGNATURE_A_MAJOR,
  KEY_SIGNATURE_E_MAJOR,
  KEY_SIGNATURE_B_MAJOR,
  KEY_SIGNATURE_F_SHARP_MAJOR,
  KEY_SIGNATURE_C_SHARP_MAJOR,    /* 7 sharps */
  /* minor keys */
  KEY_SIGNATURE_A_FLAT_MINOR,     /* 7 flats  */
  KEY_SIGNATURE_E_FLAT_MINOR,
  KEY_SIGNATURE_B_FLAT_MINOR,
  KEY_SIGNATURE_F_MINOR,
  KEY_SIGNATURE_C_MINOR,
  KEY_SIGNATURE_G_MINOR,
  KEY_SIGNATURE_D_MINOR,
  KEY_SIGNATURE_A_MINOR,          /* clear    */
  KEY_SIGNATURE_E_MINOR,
  KEY_SIGNATURE_B_MINOR,
  KEY_SIGNATURE_F_SHARP_MINOR,
  KEY_SIGNATURE_C_SHARP_MINOR,
  KEY_SIGNATURE_G_SHARP_MINOR,
  KEY_SIGNATURE_D_SHARP_MINOR,
  KEY_SIGNATURE_A_SHARP_MINOR,    /* 7 sharps */
  KEY_NUM_SIGNATURES
};
#endif

enum
{
  KEY_SIGNATURE_7_FLAT = 0, 
  KEY_SIGNATURE_6_FLAT, 
  KEY_SIGNATURE_5_FLAT, 
  KEY_SIGNATURE_4_FLAT, 
  KEY_SIGNATURE_3_FLAT, 
  KEY_SIGNATURE_2_FLAT, 
  KEY_SIGNATURE_1_FLAT, 
  KEY_SIGNATURE_CLEAR, 
  KEY_SIGNATURE_1_SHARP, 
  KEY_SIGNATURE_2_SHARP, 
  KEY_SIGNATURE_3_SHARP, 
  KEY_SIGNATURE_4_SHARP, 
  KEY_SIGNATURE_5_SHARP, 
  KEY_SIGNATURE_6_SHARP, 
  KEY_SIGNATURE_7_SHARP, 
  KEY_NUM_SIGNATURES
};

enum
{
  KEY_MODE_IONIAN = 0,  /* major */
  KEY_MODE_DORIAN, 
  KEY_MODE_PHRYGIAN, 
  KEY_MODE_LYDIAN, 
  KEY_MODE_MIXOLYDIAN, 
  KEY_MODE_AEOLIAN,     /* minor */
  KEY_MODE_LOCRIAN, 
  KEY_NUM_MODES
};

enum
{
  KEY_DEGREE_TONIC = 0, 
  KEY_DEGREE_SECOND, 
  KEY_DEGREE_THIRD, 
  KEY_DEGREE_FOURTH, 
  KEY_DEGREE_FIFTH, 
  KEY_DEGREE_SIXTH, 
  KEY_DEGREE_SEVENTH, 
  KEY_NUM_DEGREES
};

enum
{
  KEY_NOTE_C = 0, 
  KEY_NOTE_C_SHARP, 
  KEY_NOTE_D, 
  KEY_NOTE_D_SHARP, 
  KEY_NOTE_E, 
  KEY_NOTE_F, 
  KEY_NOTE_F_SHARP, 
  KEY_NOTE_G, 
  KEY_NOTE_G_SHARP, 
  KEY_NOTE_A, 
  KEY_NOTE_A_SHARP, 
  KEY_NOTE_B, 
  KEY_NUM_NOTES
};

enum
{
  KEY_HIGHLIGHT_OFF = 0,
  KEY_HIGHLIGHT_ON, 
  KEY_HIGHLIGHT_TONIC
};

/* note table */
extern char G_key_highlight_table[KEY_NUM_NOTES];

/* function declarations */
short int   key_set_current_key(int signature, int mode);

short int   key_generate_tables();

#endif
