/*******************************************************************************
** layout.h (screen layout widget positions)
*******************************************************************************/

#ifndef LAYOUT_H
#define LAYOUT_H

/* top panel buttons */
enum
{
  LAYOUT_BUTTON_LABEL_PATCHES = 0, 
  LAYOUT_BUTTON_LABEL_PATTERNS 
};

enum
{
  LAYOUT_BUTTON_STATE_OFF = 0, 
  LAYOUT_BUTTON_STATE_ON 
};

/* top panel */
enum
{
  LAYOUT_TOP_PANEL_HEADER_LABEL_NAME = 0,
  LAYOUT_TOP_PANEL_HEADER_LABEL_VERSION, 
  LAYOUT_TOP_PANEL_HEADER_NUM_LABELS
};

/* patch edit screen */
enum
{
  LAYOUT_PATCH_EDIT_HEADER_LABEL_OSC_1 = 0, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_OSC_2, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_OSC_3, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_OSC_4, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_ENV_1, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_ENV_2, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_ENV_3, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_ENV_4, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_LFO, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_VIBRATO, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_TREMOLO, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_PORTAMENTO, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_PEDAL, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_BOOST, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_EFFECTS, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_PITCH_WHEEL, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_SYNC, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_VELOCITY, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_NOISE, 
  LAYOUT_PATCH_EDIT_HEADER_LABEL_FILTERS, 
  LAYOUT_PATCH_EDIT_HEADER_NUM_LABELS
};

enum
{
  LAYOUT_PATCH_EDIT_PARAM_LABEL_CART_NUMBER = 0, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_CART_NAME, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PATCH_NUMBER, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PATCH_NAME, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ALGORITHM, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ALG_NAME, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_WAVEFORM, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_PHI, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_FREQ_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_MULTIPLE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_DIVISOR, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_NOTE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_OCTAVE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_DETUNE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_FEEDBACK, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_ATTACK, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_DECAY_1, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_DECAY_2, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_RELEASE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_AMPLITUDE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_SUSTAIN, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_RATE_KS, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_LEVEL_KS, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_BREAK_POINT, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_LFO_WAVEFORM, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_LFO_FREQUENCY, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_LFO_DELAY, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_LFO_QUANTIZE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_VIBRATO_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_VIBRATO_DEPTH, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_VIBRATO_BASE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_TREMOLO_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_TREMOLO_DEPTH, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_TREMOLO_BASE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PORTAMENTO_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PORTAMENTO_LEGATO, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PORTAMENTO_SPEED, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PEDAL_ADJUST, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_BOOST_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_BOOST_DEPTH, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_MOD_WHEEL_EFFECT, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_AFTERTOUCH_EFFECT, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PITCH_WHEEL_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_PITCH_WHEEL_RANGE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_SYNC_OSC, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_SYNC_LFO, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_VELOCITY_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_VELOCITY_SCALING, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_NOISE_MODE, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_NOISE_FREQUENCY, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_HIGHPASS_CUTOFF, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_LOWPASS_CUTOFF, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_AUDITION_VELOCITY, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_AUDITION_MOD_WHEEL, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_AUDITION_AFTERTOUCH, 
  LAYOUT_PATCH_EDIT_PARAM_LABEL_AUDITION_PITCH_WHEEL, 
  LAYOUT_PATCH_EDIT_PARAM_NUM_LABELS
};

enum
{
  LAYOUT_PATCH_EDIT_PARAM_TYPE_SLIDER = 0, 
  LAYOUT_PATCH_EDIT_PARAM_TYPE_ARROWS, 
  LAYOUT_PATCH_EDIT_PARAM_TYPE_RADIO, 
  LAYOUT_PATCH_EDIT_PARAM_TYPE_NAME 
};

/* for the patch edit parameters, there are 4 copies of the oscillator & envelope labels */
#define LAYOUT_PATCH_EDIT_PARAM_FIRST_OSC_ENV_LABEL LAYOUT_PATCH_EDIT_PARAM_LABEL_OSC_WAVEFORM
#define LAYOUT_PATCH_EDIT_PARAM_LAST_OSC_ENV_LABEL  LAYOUT_PATCH_EDIT_PARAM_LABEL_ENV_BREAK_POINT

#define LAYOUT_PATCH_EDIT_PARAM_NUM_OSC_ENV_LABELS  (LAYOUT_PATCH_EDIT_PARAM_LAST_OSC_ENV_LABEL - LAYOUT_PATCH_EDIT_PARAM_FIRST_OSC_ENV_LABEL + 1)
#define LAYOUT_PATCH_EDIT_PARAM_NUM_OTHER_LABELS    (LAYOUT_PATCH_EDIT_PARAM_NUM_LABELS - LAYOUT_PATCH_EDIT_PARAM_NUM_OSC_ENV_LABELS)

#define LAYOUT_PATCH_EDIT_PARAM_FIRST_OSC_ENV_INDEX LAYOUT_PATCH_EDIT_PARAM_FIRST_OSC_ENV_LABEL
#define LAYOUT_PATCH_EDIT_PARAM_LAST_OSC_ENV_INDEX  (LAYOUT_PATCH_EDIT_PARAM_FIRST_OSC_ENV_INDEX + 4 * LAYOUT_PATCH_EDIT_PARAM_NUM_OSC_ENV_LABELS - 1)

/* buttons */
#define LAYOUT_NUM_TOP_PANEL_BUTTONS  2
#define LAYOUT_NUM_PATCHES_BUTTONS    0

#define LAYOUT_NUM_BUTTONS    ( LAYOUT_NUM_TOP_PANEL_BUTTONS +                 \
                                LAYOUT_NUM_PATCHES_BUTTONS)

#define LAYOUT_TOP_PANEL_BUTTONS_START_INDEX   0
#define LAYOUT_TOP_PANEL_BUTTONS_END_INDEX     (LAYOUT_TOP_PANEL_BUTTONS_START_INDEX + \
                                                LAYOUT_NUM_TOP_PANEL_BUTTONS)

#define LAYOUT_PATCHES_BUTTONS_START_INDEX   LAYOUT_TOP_PANEL_BUTTONS_END_INDEX
#define LAYOUT_PATCHES_BUTTONS_END_INDEX     (LAYOUT_PATCHES_BUTTONS_START_INDEX + \
                                              LAYOUT_NUM_PATCHES_BUTTONS)

#define LAYOUT_BUTTON_INDEX_IS_VALID(index)                                    \
  ((index >= 0) && (index < LAYOUT_NUM_BUTTONS))

#define LAYOUT_BUTTON_INDEX_IS_NOT_VALID(index)                                \
  (!(LAYOUT_BUTTON_INDEX_IS_VALID(index)))

/* headers */
#define LAYOUT_NUM_TOP_PANEL_HEADERS    LAYOUT_TOP_PANEL_HEADER_NUM_LABELS
#define LAYOUT_NUM_PATCH_EDIT_HEADERS   LAYOUT_PATCH_EDIT_HEADER_NUM_LABELS

#define LAYOUT_NUM_HEADERS    ( LAYOUT_NUM_TOP_PANEL_HEADERS +                 \
                                LAYOUT_NUM_PATCH_EDIT_HEADERS)

#define LAYOUT_TOP_PANEL_HEADERS_START_INDEX   0
#define LAYOUT_TOP_PANEL_HEADERS_END_INDEX     (LAYOUT_TOP_PANEL_HEADERS_START_INDEX + \
                                                LAYOUT_NUM_TOP_PANEL_HEADERS)

#define LAYOUT_PATCH_EDIT_HEADERS_START_INDEX   LAYOUT_TOP_PANEL_HEADERS_END_INDEX
#define LAYOUT_PATCH_EDIT_HEADERS_END_INDEX     ( LAYOUT_PATCH_EDIT_HEADERS_START_INDEX + \
                                                  LAYOUT_NUM_PATCH_EDIT_HEADERS)

#define LAYOUT_HEADER_INDEX_IS_VALID(index)                                    \
  ((index >= 0) && (index < LAYOUT_NUM_HEADERS))

#define LAYOUT_HEADER_INDEX_IS_NOT_VALID(index)                                \
  (!(LAYOUT_HEADER_INDEX_IS_VALID(index)))

/* params */
#define LAYOUT_NUM_PATCH_EDIT_PARAMS  (LAYOUT_PATCH_EDIT_PARAM_NUM_OTHER_LABELS + (4 * LAYOUT_PATCH_EDIT_PARAM_NUM_OSC_ENV_LABELS))
#define LAYOUT_NUM_BANK_EDIT_PARAMS   0

#define LAYOUT_NUM_PARAMS   ( LAYOUT_NUM_PATCH_EDIT_PARAMS +                   \
                              LAYOUT_NUM_BANK_EDIT_PARAMS)

#define LAYOUT_PATCH_EDIT_PARAMS_START_INDEX  0
#define LAYOUT_PATCH_EDIT_PARAMS_END_INDEX    ( LAYOUT_PATCH_EDIT_PARAMS_START_INDEX + \
                                                LAYOUT_NUM_PATCH_EDIT_PARAMS)

#define LAYOUT_BANK_EDIT_PARAMS_START_INDEX   LAYOUT_PATCH_EDIT_PARAMS_END_INDEX
#define LAYOUT_BANK_EDIT_PARAMS_END_INDEX     ( LAYOUT_BANK_EDIT_PARAMS_START_INDEX + \
                                                LAYOUT_NUM_BANK_EDIT_PARAMS)

#define LAYOUT_PARAM_INDEX_IS_VALID(index)                                     \
  ((index >= 0) && (index < LAYOUT_NUM_PARAMS))

#define LAYOUT_PARAM_INDEX_IS_NOT_VALID(index)                                 \
  (!(LAYOUT_PARAM_INDEX_IS_VALID(index)))

/* screen areas positions & sizes */
#define LAYOUT_TOP_PANEL_AREA_X        0
#define LAYOUT_TOP_PANEL_AREA_Y      -22
#define LAYOUT_TOP_PANEL_AREA_WIDTH   50
#define LAYOUT_TOP_PANEL_AREA_HEIGHT   6

#define LAYOUT_SCROLLBAR_AREA_X       49
#define LAYOUT_SCROLLBAR_AREA_Y        6
#define LAYOUT_SCROLLBAR_AREA_WIDTH    1
#define LAYOUT_SCROLLBAR_AREA_HEIGHT  22

#define LAYOUT_PATCH_EDIT_MAIN_AREA_X      -1
#define LAYOUT_PATCH_EDIT_MAIN_AREA_Y       3
#define LAYOUT_PATCH_EDIT_MAIN_AREA_WIDTH  49
#define LAYOUT_PATCH_EDIT_MAIN_AREA_HEIGHT 19

#define LAYOUT_PATCH_EDIT_BAR_AREA_X       -1
#define LAYOUT_PATCH_EDIT_BAR_AREA_Y       25
#define LAYOUT_PATCH_EDIT_BAR_AREA_WIDTH   49
#define LAYOUT_PATCH_EDIT_BAR_AREA_HEIGHT   3

/* screen regions (divided vertically) */
#define LAYOUT_PATCH_HEADER_OR_PARAM_IS_IN_PATCH_EDIT_MAIN_AREA(pos_y)                      \
  ( (pos_y >  (LAYOUT_PATCH_EDIT_MAIN_AREA_Y - LAYOUT_PATCH_EDIT_MAIN_AREA_HEIGHT + 1)) &&  \
    (pos_y <  (LAYOUT_PATCH_EDIT_MAIN_AREA_Y + LAYOUT_PATCH_EDIT_MAIN_AREA_HEIGHT - 2)))

#define LAYOUT_PATCH_HEADER_OR_PARAM_IS_NOT_IN_PATCH_EDIT_MAIN_AREA(pos_y)                  \
  (!(LAYOUT_PATCH_HEADER_OR_PARAM_IS_IN_PATCH_EDIT_MAIN_AREA(pos_y)))

/* vertical scrollbar amounts */
#define LAYOUT_PATCH_EDIT_MAX_SCROLL_AMOUNT   70
#define LAYOUT_PATTERN_EDIT_MAX_SCROLL_AMOUNT  0

/* top panel header positions */
#define LAYOUT_TOP_PANEL_HEADER_NAME_X       -5
#define LAYOUT_TOP_PANEL_HEADER_NAME_Y      -24

#define LAYOUT_TOP_PANEL_HEADER_VERSION_X     9
#define LAYOUT_TOP_PANEL_HEADER_VERSION_Y   -24

/* top panel button positions & sizes */
#define LAYOUT_TOP_PANEL_BUTTON_PATCHES_X       -40
#define LAYOUT_TOP_PANEL_BUTTON_PATCHES_Y       -20
#define LAYOUT_TOP_PANEL_BUTTON_PATCHES_WIDTH     8

#define LAYOUT_TOP_PANEL_BUTTON_PATTERNS_X      -22
#define LAYOUT_TOP_PANEL_BUTTON_PATTERNS_Y      -20
#define LAYOUT_TOP_PANEL_BUTTON_PATTERNS_WIDTH   10

/* patch edit position macros */
#define LAYOUT_PATCH_EDIT_COMPUTE_NEXT_HEADER_Y(last_header, row)              \
  (last_header + 4 * 2 + 3 * row)

#define LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(header_name, row)                    \
  (header_name + 4 * 1 + 3 * row)

/* patch edit divider */
#define LAYOUT_PATCH_DIVIDER_X      -1
#define LAYOUT_PATCH_DIVIDER_Y      22
#define LAYOUT_PATCH_DIVIDER_WIDTH  46

/* patch edit headers & adjustable parameters */
#define LAYOUT_PATCH_EDIT_COLUMN_1_CENTER_X  -37
#define LAYOUT_PATCH_EDIT_COLUMN_2_CENTER_X  -13
#define LAYOUT_PATCH_EDIT_COLUMN_3_CENTER_X   11
#define LAYOUT_PATCH_EDIT_COLUMN_4_CENTER_X   35

#define LAYOUT_PATCH_EDIT_CART_NUMBER_Y      -13
#define LAYOUT_PATCH_EDIT_PATCH_NUMBER_Y      -9

#define LAYOUT_PATCH_EDIT_ALGORITHM_Y         -5

#define LAYOUT_PATCH_EDIT_HEADER_OSC_Y        -1

#define LAYOUT_PATCH_EDIT_OSC_WAVEFORM_Y      LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 0)
#define LAYOUT_PATCH_EDIT_OSC_PHI_Y           LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 1)
#define LAYOUT_PATCH_EDIT_OSC_FREQ_MODE_Y     LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 2)
#define LAYOUT_PATCH_EDIT_OSC_MULTIPLE_Y      LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 3)
#define LAYOUT_PATCH_EDIT_OSC_DIVISOR_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 4)
#define LAYOUT_PATCH_EDIT_OSC_DETUNE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 5)
#define LAYOUT_PATCH_EDIT_OSC_FEEDBACK_Y      LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 6)

#define LAYOUT_PATCH_EDIT_OSC_NOTE_Y          LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 3)
#define LAYOUT_PATCH_EDIT_OSC_OCTAVE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 4)

#define LAYOUT_PATCH_EDIT_HEADER_ENV_Y        LAYOUT_PATCH_EDIT_COMPUTE_NEXT_HEADER_Y(LAYOUT_PATCH_EDIT_HEADER_OSC_Y, 6)

#define LAYOUT_PATCH_EDIT_ENV_ATTACK_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 0)
#define LAYOUT_PATCH_EDIT_ENV_DECAY_1_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 1)
#define LAYOUT_PATCH_EDIT_ENV_DECAY_2_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 2)
#define LAYOUT_PATCH_EDIT_ENV_RELEASE_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 3)
#define LAYOUT_PATCH_EDIT_ENV_AMPLITUDE_Y     LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 4)
#define LAYOUT_PATCH_EDIT_ENV_SUSTAIN_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 5)
#define LAYOUT_PATCH_EDIT_ENV_RATE_KS_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 6)
#define LAYOUT_PATCH_EDIT_ENV_LEVEL_KS_Y      LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 7)
#define LAYOUT_PATCH_EDIT_ENV_BREAK_POINT_Y   LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 8)

#define LAYOUT_PATCH_EDIT_HEADER_LFO_X          LAYOUT_PATCH_EDIT_COLUMN_1_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_LFO_Y          LAYOUT_PATCH_EDIT_COMPUTE_NEXT_HEADER_Y(LAYOUT_PATCH_EDIT_HEADER_ENV_Y, 8)

#define LAYOUT_PATCH_EDIT_LFO_WAVEFORM_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_LFO_Y, 0)
#define LAYOUT_PATCH_EDIT_LFO_FREQUENCY_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_LFO_Y, 1)
#define LAYOUT_PATCH_EDIT_LFO_DELAY_Y           LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_LFO_Y, 2)
#define LAYOUT_PATCH_EDIT_LFO_QUANTIZE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_LFO_Y, 3)

#define LAYOUT_PATCH_EDIT_HEADER_VIBRATO_X      LAYOUT_PATCH_EDIT_COLUMN_2_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_VIBRATO_Y      LAYOUT_PATCH_EDIT_HEADER_LFO_Y

#define LAYOUT_PATCH_EDIT_VIBRATO_MODE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_VIBRATO_Y, 0)
#define LAYOUT_PATCH_EDIT_VIBRATO_DEPTH_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_VIBRATO_Y, 1)
#define LAYOUT_PATCH_EDIT_VIBRATO_BASE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_VIBRATO_Y, 2)

#define LAYOUT_PATCH_EDIT_HEADER_TREMOLO_X      LAYOUT_PATCH_EDIT_COLUMN_3_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_TREMOLO_Y      LAYOUT_PATCH_EDIT_HEADER_LFO_Y

#define LAYOUT_PATCH_EDIT_TREMOLO_MODE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_TREMOLO_Y, 0)
#define LAYOUT_PATCH_EDIT_TREMOLO_DEPTH_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_TREMOLO_Y, 1)
#define LAYOUT_PATCH_EDIT_TREMOLO_BASE_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_TREMOLO_Y, 2)

#define LAYOUT_PATCH_EDIT_HEADER_PORTAMENTO_X   LAYOUT_PATCH_EDIT_COLUMN_4_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_PORTAMENTO_Y   LAYOUT_PATCH_EDIT_HEADER_LFO_Y

#define LAYOUT_PATCH_EDIT_PORTAMENTO_MODE_Y     LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_PORTAMENTO_Y, 0)
#define LAYOUT_PATCH_EDIT_PORTAMENTO_LEGATO_Y   LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_PORTAMENTO_Y, 1)
#define LAYOUT_PATCH_EDIT_PORTAMENTO_SPEED_Y    LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_PORTAMENTO_Y, 2)

#define LAYOUT_PATCH_EDIT_HEADER_PEDAL_X        LAYOUT_PATCH_EDIT_COLUMN_1_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_PEDAL_Y        LAYOUT_PATCH_EDIT_COMPUTE_NEXT_HEADER_Y(LAYOUT_PATCH_EDIT_HEADER_LFO_Y, 3)

#define LAYOUT_PATCH_EDIT_PEDAL_ADJUST_Y        LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_PEDAL_Y, 0)

#define LAYOUT_PATCH_EDIT_HEADER_BOOST_X        LAYOUT_PATCH_EDIT_COLUMN_2_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_BOOST_Y        LAYOUT_PATCH_EDIT_COMPUTE_NEXT_HEADER_Y(LAYOUT_PATCH_EDIT_HEADER_PORTAMENTO_Y, 2)

#define LAYOUT_PATCH_EDIT_BOOST_MODE_Y          LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_BOOST_Y, 0)
#define LAYOUT_PATCH_EDIT_BOOST_DEPTH_Y         LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_BOOST_Y, 1)

#define LAYOUT_PATCH_EDIT_HEADER_EFFECTS_X      LAYOUT_PATCH_EDIT_COLUMN_3_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_EFFECTS_Y      LAYOUT_PATCH_EDIT_HEADER_BOOST_Y

#define LAYOUT_PATCH_EDIT_MOD_WHEEL_EFFECT_Y    LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_EFFECTS_Y, 0)
#define LAYOUT_PATCH_EDIT_AFTERTOUCH_EFFECT_Y   LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_EFFECTS_Y, 1)

#define LAYOUT_PATCH_EDIT_HEADER_PITCH_WHEEL_X  LAYOUT_PATCH_EDIT_COLUMN_4_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_PITCH_WHEEL_Y  LAYOUT_PATCH_EDIT_HEADER_BOOST_Y

#define LAYOUT_PATCH_EDIT_PITCH_WHEEL_MODE_Y    LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_PITCH_WHEEL_Y, 0)
#define LAYOUT_PATCH_EDIT_PITCH_WHEEL_RANGE_Y   LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_PITCH_WHEEL_Y, 1)

#define LAYOUT_PATCH_EDIT_HEADER_SYNC_X         LAYOUT_PATCH_EDIT_COLUMN_1_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_SYNC_Y         LAYOUT_PATCH_EDIT_COMPUTE_NEXT_HEADER_Y(LAYOUT_PATCH_EDIT_HEADER_PEDAL_Y, 0)

#define LAYOUT_PATCH_EDIT_SYNC_OSC_Y            LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_SYNC_Y, 0)
#define LAYOUT_PATCH_EDIT_SYNC_LFO_Y            LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_SYNC_Y, 1)

#define LAYOUT_PATCH_EDIT_HEADER_VELOCITY_X     LAYOUT_PATCH_EDIT_COLUMN_2_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_VELOCITY_Y     LAYOUT_PATCH_EDIT_HEADER_SYNC_Y

#define LAYOUT_PATCH_EDIT_VELOCITY_MODE_Y       LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_VELOCITY_Y, 0)
#define LAYOUT_PATCH_EDIT_VELOCITY_SCALING_Y    LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_VELOCITY_Y, 1)

#define LAYOUT_PATCH_EDIT_HEADER_NOISE_X        LAYOUT_PATCH_EDIT_COLUMN_3_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_NOISE_Y        LAYOUT_PATCH_EDIT_HEADER_SYNC_Y

#define LAYOUT_PATCH_EDIT_NOISE_MODE_Y          LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_NOISE_Y, 0)
#define LAYOUT_PATCH_EDIT_NOISE_FREQUENCY_Y     LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_NOISE_Y, 1)

#define LAYOUT_PATCH_EDIT_HEADER_FILTERS_X      LAYOUT_PATCH_EDIT_COLUMN_4_CENTER_X
#define LAYOUT_PATCH_EDIT_HEADER_FILTERS_Y      LAYOUT_PATCH_EDIT_HEADER_SYNC_Y

#define LAYOUT_PATCH_EDIT_HIGHPASS_CUTOFF_Y     LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_FILTERS_Y, 0)
#define LAYOUT_PATCH_EDIT_LOWPASS_CUTOFF_Y      LAYOUT_PATCH_EDIT_COMPUTE_PARAM_Y(LAYOUT_PATCH_EDIT_HEADER_FILTERS_Y, 1)

#define LAYOUT_PATCH_EDIT_AUDITION_VELOCITY_Y     25
#define LAYOUT_PATCH_EDIT_AUDITION_MOD_WHEEL_Y    25
#define LAYOUT_PATCH_EDIT_AUDITION_AFTERTOUCH_Y   25
#define LAYOUT_PATCH_EDIT_AUDITION_PITCH_WHEEL_Y  25

#define LAYOUT_PATCH_EDIT_PARAM_NAME_X          -8

#define LAYOUT_PATCH_EDIT_PARAM_SLIDER_VALUE_X  -2
#define LAYOUT_PATCH_EDIT_PARAM_SLIDER_TRACK_X   6
#define LAYOUT_PATCH_EDIT_PARAM_SLIDER_WIDTH     5

#define LAYOUT_PATCH_EDIT_PARAM_ARROWS_LEFT_X   -2
#define LAYOUT_PATCH_EDIT_PARAM_ARROWS_VALUE_X   4
#define LAYOUT_PATCH_EDIT_PARAM_ARROWS_RIGHT_X  10

#define LAYOUT_PATCH_EDIT_PARAM_RADIO_BUTTON_X  -2
#define LAYOUT_PATCH_EDIT_PARAM_RADIO_VALUE_X    6

typedef struct button
{
  int label;

  int center_x;
  int center_y;

  int width;
  int state;
} button;

typedef struct header
{
  int label;

  int center_x;
  int center_y;
} header;

typedef struct param
{
  int label;
  int num;

  int type;

  int center_x;
  int center_y;

  short int lower_bound;
  short int upper_bound;
} param;

extern button G_layout_buttons[LAYOUT_NUM_BUTTONS];
extern header G_layout_headers[LAYOUT_NUM_HEADERS];
extern param  G_layout_params[LAYOUT_NUM_PARAMS];

/* function declarations */
short int layout_setup_all();

short int layout_reset_top_panel_button_states();

#endif
