/*******************************************************************************
** layout.h (screen layout widget positions)
*******************************************************************************/

#ifndef LAYOUT_H
#define LAYOUT_H

enum
{
  LAYOUT_PANEL_TYPE_1 = 1, 
  LAYOUT_PANEL_TYPE_2 
};

enum
{
  LAYOUT_BUTTON_STATE_OFF = 0, 
  LAYOUT_BUTTON_STATE_ON 
};

enum
{
  LAYOUT_PARAM_TYPE_SLIDER = 0, 
  LAYOUT_PARAM_TYPE_ARROWS, 
  LAYOUT_PARAM_TYPE_RADIO, 
  LAYOUT_PARAM_TYPE_NAME 
};

/* top panel */
enum
{
  LAYOUT_TOP_PANEL_BUTTON_LABEL_CART = 0, 
  LAYOUT_TOP_PANEL_BUTTON_LABEL_INSTRUMENTS, 
  LAYOUT_TOP_PANEL_BUTTON_LABEL_SONG, 
  LAYOUT_TOP_PANEL_BUTTON_LABEL_MIXER, 
  LAYOUT_TOP_PANEL_BUTTON_LABEL_SOUND_FX, 
  LAYOUT_TOP_PANEL_BUTTON_LABEL_DPCM, 
  LAYOUT_TOP_PANEL_BUTTON_NUM_LABELS
};

enum
{
  LAYOUT_TOP_PANEL_HEADER_LABEL_NAME = 0,
  LAYOUT_TOP_PANEL_HEADER_LABEL_VERSION, 
  LAYOUT_TOP_PANEL_HEADER_NUM_LABELS
};

/* cart screen */
enum
{
  LAYOUT_CART_BUTTON_LABEL_CART_LOAD = 0, 
  LAYOUT_CART_BUTTON_LABEL_CART_SAVE, 
  LAYOUT_CART_BUTTON_LABEL_CART_COPY, 
  LAYOUT_CART_BUTTON_LABEL_CART_ZAP, 
  LAYOUT_CART_BUTTON_LABEL_PATCH_LOAD, 
  LAYOUT_CART_BUTTON_LABEL_PATCH_SAVE, 
  LAYOUT_CART_BUTTON_LABEL_PATCH_COPY, 
  LAYOUT_CART_BUTTON_LABEL_PATCH_ZAP, 
  LAYOUT_CART_BUTTON_NUM_LABELS
};

enum
{
  LAYOUT_CART_HEADER_LABEL_OSC_1 = 0, 
  LAYOUT_CART_HEADER_LABEL_OSC_2, 
  LAYOUT_CART_HEADER_LABEL_LOWPASS, 
  LAYOUT_CART_HEADER_LABEL_HIGHPASS, 
  LAYOUT_CART_HEADER_LABEL_AMP_ENV, 
  LAYOUT_CART_HEADER_LABEL_FILTER_ENV, 
  LAYOUT_CART_HEADER_LABEL_EXTRA_ENV, 
  LAYOUT_CART_HEADER_LABEL_PORTAMENTO, 
  LAYOUT_CART_HEADER_LABEL_ARPEGGIO, 
  LAYOUT_CART_HEADER_LABEL_LFO, 
  LAYOUT_CART_HEADER_LABEL_VIBRATO, 
  LAYOUT_CART_HEADER_LABEL_TREMOLO, 
  LAYOUT_CART_HEADER_LABEL_EFFECTS, 
  LAYOUT_CART_HEADER_LABEL_PEDAL, 
  LAYOUT_CART_HEADER_LABEL_VELOCITY, 
  LAYOUT_CART_HEADER_LABEL_SYNC, 
  LAYOUT_CART_HEADER_LABEL_BOOST, 
  LAYOUT_CART_HEADER_LABEL_PITCH_WHEEL, 
  LAYOUT_CART_HEADER_NUM_LABELS
};

enum
{
  LAYOUT_CART_PARAM_LABEL_CART_NUMBER = 0, 
  LAYOUT_CART_PARAM_LABEL_CART_NAME, 
  LAYOUT_CART_PARAM_LABEL_PATCH_NUMBER, 
  LAYOUT_CART_PARAM_LABEL_PATCH_NAME, 
  LAYOUT_CART_PARAM_LABEL_PROGRAM, 
  LAYOUT_CART_PARAM_LABEL_PROG_NAME, 
  LAYOUT_CART_PARAM_LABEL_OSC_1_WAVEFORM, 
  LAYOUT_CART_PARAM_LABEL_OSC_1_DETUNE, 
  LAYOUT_CART_PARAM_LABEL_OSC_2_WAVEFORM, 
  LAYOUT_CART_PARAM_LABEL_OSC_2_DETUNE, 
  LAYOUT_CART_PARAM_LABEL_OSC_2_MULTIPLE, 
  LAYOUT_CART_PARAM_LABEL_OSC_2_DIVISOR, 
  LAYOUT_CART_PARAM_LABEL_LOWPASS_MULTIPLE, 
  LAYOUT_CART_PARAM_LABEL_LOWPASS_DIVISOR, 
  LAYOUT_CART_PARAM_LABEL_LOWPASS_KEYTRACKING, 
  LAYOUT_CART_PARAM_LABEL_HIGHPASS_CUTOFF, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_ATTACK, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_DECAY_1, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_DECAY_2, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_RELEASE, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_SUSTAIN, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_RATE_KS, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_LEFT_KS, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_RIGHT_KS, 
  LAYOUT_CART_PARAM_LABEL_AMP_ENV_BREAK_POINT, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_ATTACK, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_DECAY_1, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_DECAY_2, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_RELEASE, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_AMPLITUDE, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_SUSTAIN, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_HOLD, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_FINALE, 
  LAYOUT_CART_PARAM_LABEL_FILTER_ENV_RATE_KS, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_ATTACK, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_DECAY_1, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_DECAY_2, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_RELEASE, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_AMPLITUDE, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_SUSTAIN, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_HOLD, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_FINALE, 
  LAYOUT_CART_PARAM_LABEL_EXTRA_ENV_RATE_KS, 
  LAYOUT_CART_PARAM_LABEL_PORTAMENTO_MODE, 
  LAYOUT_CART_PARAM_LABEL_PORTAMENTO_FOLLOW, 
  LAYOUT_CART_PARAM_LABEL_PORTAMENTO_LEGATO, 
  LAYOUT_CART_PARAM_LABEL_PORTAMENTO_SPEED, 
  LAYOUT_CART_PARAM_LABEL_ARPEGGIO_MODE, 
  LAYOUT_CART_PARAM_LABEL_ARPEGGIO_PATTERN, 
  LAYOUT_CART_PARAM_LABEL_ARPEGGIO_OCTAVES, 
  LAYOUT_CART_PARAM_LABEL_ARPEGGIO_SPEED, 
  LAYOUT_CART_PARAM_LABEL_LFO_WAVEFORM, 
  LAYOUT_CART_PARAM_LABEL_LFO_FREQUENCY, 
  LAYOUT_CART_PARAM_LABEL_LFO_DELAY, 
  LAYOUT_CART_PARAM_LABEL_LFO_QUANTIZE, 
  LAYOUT_CART_PARAM_LABEL_VIBRATO_MODE, 
  LAYOUT_CART_PARAM_LABEL_VIBRATO_DEPTH, 
  LAYOUT_CART_PARAM_LABEL_VIBRATO_BASE, 
  LAYOUT_CART_PARAM_LABEL_TREMOLO_MODE, 
  LAYOUT_CART_PARAM_LABEL_TREMOLO_DEPTH, 
  LAYOUT_CART_PARAM_LABEL_TREMOLO_BASE, 
  LAYOUT_CART_PARAM_LABEL_MOD_WHEEL_EFFECT, 
  LAYOUT_CART_PARAM_LABEL_AFTERTOUCH_EFFECT, 
  LAYOUT_CART_PARAM_LABEL_EXP_PEDAL_EFFECT, 
  LAYOUT_CART_PARAM_LABEL_PEDAL_ADJUST, 
  LAYOUT_CART_PARAM_LABEL_VELOCITY_MODE, 
  LAYOUT_CART_PARAM_LABEL_VELOCITY_SCALING, 
  LAYOUT_CART_PARAM_LABEL_SYNC_OSC, 
  LAYOUT_CART_PARAM_LABEL_SYNC_LFO, 
  LAYOUT_CART_PARAM_LABEL_BOOST_MODE, 
  LAYOUT_CART_PARAM_LABEL_BOOST_DEPTH, 
  LAYOUT_CART_PARAM_LABEL_PITCH_WHEEL_MODE, 
  LAYOUT_CART_PARAM_LABEL_PITCH_WHEEL_RANGE, 
  LAYOUT_CART_PARAM_LABEL_AUDITION_VELOCITY, 
  LAYOUT_CART_PARAM_LABEL_AUDITION_MOD_WHEEL, 
  LAYOUT_CART_PARAM_LABEL_AUDITION_AFTERTOUCH, 
  LAYOUT_CART_PARAM_LABEL_AUDITION_PITCH_WHEEL, 
  LAYOUT_CART_PARAM_NUM_LABELS
};

/* load screen */
enum
{
  LAYOUT_LOAD_BUTTON_LABEL_LOAD = 0, 
  LAYOUT_LOAD_BUTTON_NUM_LABELS
};

enum
{
  LAYOUT_LOAD_HEADER_LABEL_TITLE = 0, 
  LAYOUT_LOAD_HEADER_NUM_LABELS
};

/* save screen */
enum
{
  LAYOUT_SAVE_BUTTON_LABEL_SAVE = 0, 
  LAYOUT_SAVE_BUTTON_NUM_LABELS
};

enum
{
  LAYOUT_SAVE_HEADER_LABEL_TITLE = 0, 
  LAYOUT_SAVE_HEADER_NUM_LABELS
};

/* copy screen */
enum
{
  LAYOUT_COPY_BUTTON_LABEL_COPY = 0, 
  LAYOUT_COPY_BUTTON_NUM_LABELS
};

enum
{
  LAYOUT_COPY_HEADER_LABEL_TITLE = 0, 
  LAYOUT_COPY_HEADER_NUM_LABELS
};

/* zap screen */
enum
{
  LAYOUT_ZAP_BUTTON_LABEL_ZAP = 0, 
  LAYOUT_ZAP_BUTTON_NUM_LABELS
};

enum
{
  LAYOUT_ZAP_HEADER_LABEL_TITLE = 0, 
  LAYOUT_ZAP_HEADER_NUM_LABELS
};

/* screen center (in half-cells) */
#define LAYOUT_OVERSCAN_WIDTH   400
#define LAYOUT_OVERSCAN_HEIGHT  224

#define LAYOUT_OVERSCAN_CENTER_X  ((LAYOUT_OVERSCAN_WIDTH / 2) / 4)
#define LAYOUT_OVERSCAN_CENTER_Y  ((LAYOUT_OVERSCAN_HEIGHT / 2) / 4)

/* buttons */
#define LAYOUT_NUM_TOP_PANEL_BUTTONS  LAYOUT_TOP_PANEL_BUTTON_NUM_LABELS
#define LAYOUT_NUM_CART_BUTTONS       LAYOUT_CART_BUTTON_NUM_LABELS
#define LAYOUT_NUM_LOAD_BUTTONS       LAYOUT_LOAD_BUTTON_NUM_LABELS
#define LAYOUT_NUM_SAVE_BUTTONS       LAYOUT_SAVE_BUTTON_NUM_LABELS
#define LAYOUT_NUM_COPY_BUTTONS       LAYOUT_COPY_BUTTON_NUM_LABELS
#define LAYOUT_NUM_ZAP_BUTTONS        LAYOUT_ZAP_BUTTON_NUM_LABELS

#define LAYOUT_NUM_BUTTONS    ( LAYOUT_NUM_TOP_PANEL_BUTTONS +                 \
                                LAYOUT_NUM_CART_BUTTONS +                      \
                                LAYOUT_NUM_LOAD_BUTTONS +                      \
                                LAYOUT_NUM_SAVE_BUTTONS +                      \
                                LAYOUT_NUM_COPY_BUTTONS +                      \
                                LAYOUT_NUM_ZAP_BUTTONS)

#define LAYOUT_TOP_PANEL_BUTTONS_START_INDEX   0
#define LAYOUT_TOP_PANEL_BUTTONS_END_INDEX     (LAYOUT_TOP_PANEL_BUTTONS_START_INDEX + \
                                                LAYOUT_NUM_TOP_PANEL_BUTTONS)

#define LAYOUT_CART_BUTTONS_START_INDEX   LAYOUT_TOP_PANEL_BUTTONS_END_INDEX
#define LAYOUT_CART_BUTTONS_END_INDEX     ( LAYOUT_CART_BUTTONS_START_INDEX + \
                                            LAYOUT_NUM_CART_BUTTONS)

#define LAYOUT_LOAD_BUTTONS_START_INDEX   LAYOUT_CART_BUTTONS_END_INDEX
#define LAYOUT_LOAD_BUTTONS_END_INDEX     ( LAYOUT_LOAD_BUTTONS_START_INDEX + \
                                            LAYOUT_NUM_LOAD_BUTTONS)

#define LAYOUT_SAVE_BUTTONS_START_INDEX   LAYOUT_LOAD_BUTTONS_END_INDEX
#define LAYOUT_SAVE_BUTTONS_END_INDEX     ( LAYOUT_SAVE_BUTTONS_START_INDEX + \
                                            LAYOUT_NUM_SAVE_BUTTONS)

#define LAYOUT_COPY_BUTTONS_START_INDEX   LAYOUT_SAVE_BUTTONS_END_INDEX
#define LAYOUT_COPY_BUTTONS_END_INDEX     ( LAYOUT_COPY_BUTTONS_START_INDEX + \
                                            LAYOUT_NUM_COPY_BUTTONS)

#define LAYOUT_ZAP_BUTTONS_START_INDEX    LAYOUT_COPY_BUTTONS_END_INDEX
#define LAYOUT_ZAP_BUTTONS_END_INDEX      ( LAYOUT_ZAP_BUTTONS_START_INDEX + \
                                            LAYOUT_NUM_ZAP_BUTTONS)

#define LAYOUT_BUTTON_INDEX_IS_VALID(index)                                    \
  ((index >= 0) && (index < LAYOUT_NUM_BUTTONS))

#define LAYOUT_BUTTON_INDEX_IS_NOT_VALID(index)                                \
  (!(LAYOUT_BUTTON_INDEX_IS_VALID(index)))

/* headers */
#define LAYOUT_NUM_TOP_PANEL_HEADERS    LAYOUT_TOP_PANEL_HEADER_NUM_LABELS
#define LAYOUT_NUM_CART_HEADERS         LAYOUT_CART_HEADER_NUM_LABELS
#define LAYOUT_NUM_LOAD_HEADERS         LAYOUT_LOAD_HEADER_NUM_LABELS
#define LAYOUT_NUM_SAVE_HEADERS         LAYOUT_SAVE_HEADER_NUM_LABELS
#define LAYOUT_NUM_COPY_HEADERS         LAYOUT_COPY_HEADER_NUM_LABELS
#define LAYOUT_NUM_ZAP_HEADERS          LAYOUT_ZAP_HEADER_NUM_LABELS

#define LAYOUT_NUM_HEADERS    ( LAYOUT_NUM_TOP_PANEL_HEADERS +                 \
                                LAYOUT_NUM_CART_HEADERS +                      \
                                LAYOUT_NUM_LOAD_HEADERS +                      \
                                LAYOUT_NUM_SAVE_HEADERS +                      \
                                LAYOUT_NUM_COPY_HEADERS +                      \
                                LAYOUT_NUM_ZAP_HEADERS)

#define LAYOUT_TOP_PANEL_HEADERS_START_INDEX   0
#define LAYOUT_TOP_PANEL_HEADERS_END_INDEX     (LAYOUT_TOP_PANEL_HEADERS_START_INDEX + \
                                                LAYOUT_NUM_TOP_PANEL_HEADERS)

#define LAYOUT_CART_HEADERS_START_INDEX   LAYOUT_TOP_PANEL_HEADERS_END_INDEX
#define LAYOUT_CART_HEADERS_END_INDEX     ( LAYOUT_CART_HEADERS_START_INDEX + \
                                            LAYOUT_NUM_CART_HEADERS)

#define LAYOUT_LOAD_HEADERS_START_INDEX   LAYOUT_CART_HEADERS_END_INDEX
#define LAYOUT_LOAD_HEADERS_END_INDEX     ( LAYOUT_LOAD_HEADERS_START_INDEX + \
                                            LAYOUT_NUM_LOAD_HEADERS)

#define LAYOUT_SAVE_HEADERS_START_INDEX   LAYOUT_LOAD_HEADERS_END_INDEX
#define LAYOUT_SAVE_HEADERS_END_INDEX     ( LAYOUT_SAVE_HEADERS_START_INDEX + \
                                            LAYOUT_NUM_SAVE_HEADERS)

#define LAYOUT_COPY_HEADERS_START_INDEX   LAYOUT_SAVE_HEADERS_END_INDEX
#define LAYOUT_COPY_HEADERS_END_INDEX     ( LAYOUT_COPY_HEADERS_START_INDEX + \
                                            LAYOUT_NUM_COPY_HEADERS)

#define LAYOUT_ZAP_HEADERS_START_INDEX    LAYOUT_COPY_HEADERS_END_INDEX
#define LAYOUT_ZAP_HEADERS_END_INDEX      ( LAYOUT_ZAP_HEADERS_START_INDEX + \
                                            LAYOUT_NUM_ZAP_HEADERS)

#define LAYOUT_HEADER_INDEX_IS_VALID(index)                                    \
  ((index >= 0) && (index < LAYOUT_NUM_HEADERS))

#define LAYOUT_HEADER_INDEX_IS_NOT_VALID(index)                                \
  (!(LAYOUT_HEADER_INDEX_IS_VALID(index)))

/* params */
#define LAYOUT_NUM_CART_PARAMS        LAYOUT_CART_PARAM_NUM_LABELS
#define LAYOUT_NUM_INSTRUMENTS_PARAMS 0
#define LAYOUT_NUM_SONG_PARAMS        0
#define LAYOUT_NUM_MIXER_PARAMS       0
#define LAYOUT_NUM_SOUND_FX_PARAMS    0
#define LAYOUT_NUM_DPCM_PARAMS        0

#define LAYOUT_NUM_PARAMS   ( LAYOUT_NUM_CART_PARAMS +                         \
                              LAYOUT_NUM_INSTRUMENTS_PARAMS +                  \
                              LAYOUT_NUM_SONG_PARAMS +                         \
                              LAYOUT_NUM_MIXER_PARAMS +                        \
                              LAYOUT_NUM_SOUND_FX_PARAMS +                     \
                              LAYOUT_NUM_DPCM_PARAMS)

#define LAYOUT_CART_PARAMS_START_INDEX  0
#define LAYOUT_CART_PARAMS_END_INDEX    ( LAYOUT_CART_PARAMS_START_INDEX + \
                                          LAYOUT_NUM_CART_PARAMS)

#define LAYOUT_INSTRUMENTS_PARAMS_START_INDEX   LAYOUT_CART_PARAMS_END_INDEX
#define LAYOUT_INSTRUMENTS_PARAMS_END_INDEX     ( LAYOUT_INSTRUMENTS_PARAMS_START_INDEX + \
                                                  LAYOUT_INSTRUMENTS_PARAMS)

#define LAYOUT_SONG_PARAMS_START_INDEX      LAYOUT_INSTRUMENTS_PARAMS_END_INDEX
#define LAYOUT_SONG_PARAMS_END_INDEX        ( LAYOUT_SONG_PARAMS_START_INDEX + \
                                              LAYOUT_SONG_PARAMS)

#define LAYOUT_MIXER_PARAMS_START_INDEX     LAYOUT_SONG_PARAMS_END_INDEX
#define LAYOUT_MIXER_PARAMS_END_INDEX       ( LAYOUT_MIXER_PARAMS_START_INDEX + \
                                              LAYOUT_MIXER_PARAMS)

#define LAYOUT_SOUND_FX_PARAMS_START_INDEX  LAYOUT_MIXER_PARAMS_END_INDEX
#define LAYOUT_SOUND_FX_PARAMS_END_INDEX    ( LAYOUT_SOUND_FX_PARAMS_START_INDEX + \
                                              LAYOUT_SOUND_FX_PARAMS)

#define LAYOUT_DPCM_PARAMS_START_INDEX      LAYOUT_SOUND_FX_PARAMS_END_INDEX
#define LAYOUT_DPCM_PARAMS_END_INDEX        ( LAYOUT_DPCM_PARAMS_START_INDEX + \
                                              LAYOUT_DPCM_PARAMS)

#define LAYOUT_PARAM_INDEX_IS_VALID(index)                                     \
  ((index >= 0) && (index < LAYOUT_NUM_PARAMS))

#define LAYOUT_PARAM_INDEX_IS_NOT_VALID(index)                                 \
  (!(LAYOUT_PARAM_INDEX_IS_VALID(index)))

/* screen areas positions & sizes */
#define LAYOUT_TOP_PANEL_AREA_X        0
#define LAYOUT_TOP_PANEL_AREA_Y      -22
#define LAYOUT_TOP_PANEL_AREA_WIDTH   50
#define LAYOUT_TOP_PANEL_AREA_HEIGHT   6

#define LAYOUT_SCROLLBAR_AREA_X       49
#define LAYOUT_SCROLLBAR_AREA_Y        6
#define LAYOUT_SCROLLBAR_AREA_WIDTH    1
#define LAYOUT_SCROLLBAR_AREA_HEIGHT  22

#define LAYOUT_CART_MAIN_AREA_X           -1
#define LAYOUT_CART_MAIN_AREA_Y            3
#define LAYOUT_CART_MAIN_AREA_WIDTH       49
#define LAYOUT_CART_MAIN_AREA_HEIGHT      19

#define LAYOUT_CART_AUDITION_PANEL_X      -1
#define LAYOUT_CART_AUDITION_PANEL_Y      25
#define LAYOUT_CART_AUDITION_PANEL_WIDTH  49
#define LAYOUT_CART_AUDITION_PANEL_HEIGHT  3

#define LAYOUT_BROWSER_DIR_PANEL_X        -1
#define LAYOUT_BROWSER_DIR_PANEL_Y       -12
#define LAYOUT_BROWSER_DIR_PANEL_WIDTH    49
#define LAYOUT_BROWSER_DIR_PANEL_HEIGHT    4

#define LAYOUT_BROWSER_MAIN_AREA_X        -1
#define LAYOUT_BROWSER_MAIN_AREA_Y         3
#define LAYOUT_BROWSER_MAIN_AREA_WIDTH    49
#define LAYOUT_BROWSER_MAIN_AREA_HEIGHT   19

#define LAYOUT_BROWSER_FILE_PANEL_X       -1
#define LAYOUT_BROWSER_FILE_PANEL_Y       25
#define LAYOUT_BROWSER_FILE_PANEL_WIDTH   49
#define LAYOUT_BROWSER_FILE_PANEL_HEIGHT   3

/* cart edit screen regions */
#define LAYOUT_CART_HEADER_OR_PARAM_IS_IN_MAIN_AREA(pos_y)                     \
  ( (pos_y >  (LAYOUT_CART_MAIN_AREA_Y - LAYOUT_CART_MAIN_AREA_HEIGHT + 1)) && \
    (pos_y <  (LAYOUT_CART_MAIN_AREA_Y + LAYOUT_CART_MAIN_AREA_HEIGHT - 2)))

#define LAYOUT_CART_HEADER_OR_PARAM_IS_NOT_IN_MAIN_AREA(pos_y)                 \
  (!(LAYOUT_CART_HEADER_OR_PARAM_IS_IN_MAIN_AREA(pos_y)))

/* browser screen regions */
#define LAYOUT_BROWSER_FILENAME_IS_IN_MAIN_AREA(pos_y)                                \
  ( (pos_y >  (LAYOUT_BROWSER_MAIN_AREA_Y - LAYOUT_BROWSER_MAIN_AREA_HEIGHT + 1)) &&  \
    (pos_y <  (LAYOUT_BROWSER_MAIN_AREA_Y + LAYOUT_BROWSER_MAIN_AREA_HEIGHT - 2)))

#define LAYOUT_BROWSER_FILENAME_IS_NOT_IN_MAIN_AREA(pos_y)                     \
  (!(LAYOUT_BROWSER_FILENAME_IS_IN_MAIN_AREA(pos_y)))

/* vertical scrollbar amounts */
#define LAYOUT_CART_MAX_SCROLL_AMOUNT          91
#define LAYOUT_INSTRUMENTS_MAX_SCROLL_AMOUNT    0
#define LAYOUT_SONG_MAX_SCROLL_AMOUNT           0
#define LAYOUT_MIXER_MAX_SCROLL_AMOUNT          0
#define LAYOUT_SOUND_FX_MAX_SCROLL_AMOUNT       0
#define LAYOUT_DPCM_MAX_SCROLL_AMOUNT           0
#define LAYOUT_BAR_MAX_SCROLL_AMOUNT            0

/* top panel header positions */
#define LAYOUT_TOP_PANEL_HEADER_NAME_X       -5
#define LAYOUT_TOP_PANEL_HEADER_NAME_Y      -24

#define LAYOUT_TOP_PANEL_HEADER_VERSION_X     9
#define LAYOUT_TOP_PANEL_HEADER_VERSION_Y   -24

/* top panel button positions & sizes */
#define LAYOUT_TOP_PANEL_BUTTON_Y                 -20

#define LAYOUT_TOP_PANEL_BUTTON_CART_X            -42
#define LAYOUT_TOP_PANEL_BUTTON_CART_WIDTH          6

#define LAYOUT_TOP_PANEL_BUTTON_INSTRUMENTS_X     -23
#define LAYOUT_TOP_PANEL_BUTTON_INSTRUMENTS_WIDTH  13

#define LAYOUT_TOP_PANEL_BUTTON_SONG_X             -4
#define LAYOUT_TOP_PANEL_BUTTON_SONG_WIDTH          6

#define LAYOUT_TOP_PANEL_BUTTON_MIXER_X             9
#define LAYOUT_TOP_PANEL_BUTTON_MIXER_WIDTH         7

#define LAYOUT_TOP_PANEL_BUTTON_SOUND_FX_X         26
#define LAYOUT_TOP_PANEL_BUTTON_SOUND_FX_WIDTH     10

#define LAYOUT_TOP_PANEL_BUTTON_DPCM_X             42
#define LAYOUT_TOP_PANEL_BUTTON_DPCM_WIDTH          6

/* cart edit position macros */
#define LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(last_header, row)              \
  (last_header + 4 * 2 + 3 * row)

#define LAYOUT_CART_COMPUTE_PARAM_Y(header_name, row)                    \
  (header_name + 4 * 1 + 3 * row)

/* cart edit buttons, headers, and adjustable parameters */
#define LAYOUT_CART_COLUMN_1_CENTER_X    -37
#define LAYOUT_CART_COLUMN_2_CENTER_X    -13
#define LAYOUT_CART_COLUMN_3_CENTER_X     11
#define LAYOUT_CART_COLUMN_4_CENTER_X     35

/* cart number */
#define LAYOUT_CART_CART_NUMBER_Y           -13

#define LAYOUT_CART_BUTTON_CART_LOAD_X        6
#define LAYOUT_CART_BUTTON_CART_LOAD_WIDTH    6

#define LAYOUT_CART_BUTTON_CART_SAVE_X       18
#define LAYOUT_CART_BUTTON_CART_SAVE_WIDTH    6

#define LAYOUT_CART_BUTTON_CART_COPY_X       30
#define LAYOUT_CART_BUTTON_CART_COPY_WIDTH    6

#define LAYOUT_CART_BUTTON_CART_ZAP_X        41
#define LAYOUT_CART_BUTTON_CART_ZAP_WIDTH     5

/* patch number */
#define LAYOUT_CART_PATCH_NUMBER_Y           -9

#define LAYOUT_CART_BUTTON_PATCH_LOAD_X       6
#define LAYOUT_CART_BUTTON_PATCH_LOAD_WIDTH   6

#define LAYOUT_CART_BUTTON_PATCH_SAVE_X      18
#define LAYOUT_CART_BUTTON_PATCH_SAVE_WIDTH   6

#define LAYOUT_CART_BUTTON_PATCH_COPY_X      30
#define LAYOUT_CART_BUTTON_PATCH_COPY_WIDTH   6

#define LAYOUT_CART_BUTTON_PATCH_ZAP_X       41
#define LAYOUT_CART_BUTTON_PATCH_ZAP_WIDTH    5

/* divider */
#define LAYOUT_CART_MAIN_DIVIDER_X        -1
#define LAYOUT_CART_MAIN_DIVIDER_Y        -5
#define LAYOUT_CART_MAIN_DIVIDER_WIDTH    46

/* headers & parameters */
#define LAYOUT_CART_PROGRAM_X             LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_PROGRAM_Y            -1

#define LAYOUT_CART_PROG_NAME_X           LAYOUT_CART_COLUMN_2_CENTER_X
#define LAYOUT_CART_PROG_NAME_Y           LAYOUT_CART_PROGRAM_Y

#define LAYOUT_CART_HEADER_OSC_1_X        LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_HEADER_OSC_1_Y        3

#define LAYOUT_CART_OSC_1_WAVEFORM_Y      LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_OSC_1_Y, 0)
#define LAYOUT_CART_OSC_1_DETUNE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_OSC_1_Y, 1)

#define LAYOUT_CART_HEADER_OSC_2_X        LAYOUT_CART_COLUMN_2_CENTER_X
#define LAYOUT_CART_HEADER_OSC_2_Y        LAYOUT_CART_HEADER_OSC_1_Y

#define LAYOUT_CART_OSC_2_WAVEFORM_Y      LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_OSC_2_Y, 0)
#define LAYOUT_CART_OSC_2_DETUNE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_OSC_2_Y, 1)
#define LAYOUT_CART_OSC_2_MULTIPLE_Y      LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_OSC_2_Y, 2)
#define LAYOUT_CART_OSC_2_DIVISOR_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_OSC_2_Y, 3)

#define LAYOUT_CART_HEADER_LOWPASS_X      LAYOUT_CART_COLUMN_3_CENTER_X
#define LAYOUT_CART_HEADER_LOWPASS_Y      LAYOUT_CART_HEADER_OSC_2_Y

#define LAYOUT_CART_LOWPASS_MULTIPLE_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LOWPASS_Y, 0)
#define LAYOUT_CART_LOWPASS_DIVISOR_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LOWPASS_Y, 1)
#define LAYOUT_CART_LOWPASS_KEYTRACKING_Y LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LOWPASS_Y, 2)

#define LAYOUT_CART_HEADER_HIGHPASS_X     LAYOUT_CART_COLUMN_3_CENTER_X
#define LAYOUT_CART_HEADER_HIGHPASS_Y     LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_LOWPASS_Y, 2)

#define LAYOUT_CART_HIGHPASS_CUTOFF_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_HIGHPASS_Y, 0)

#define LAYOUT_CART_HEADER_AMP_ENV_X        LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_HEADER_AMP_ENV_Y        LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_HIGHPASS_Y, 0)

#define LAYOUT_CART_AMP_ENV_ATTACK_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 0)
#define LAYOUT_CART_AMP_ENV_DECAY_1_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 1)
#define LAYOUT_CART_AMP_ENV_DECAY_2_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 2)
#define LAYOUT_CART_AMP_ENV_RELEASE_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 3)
#define LAYOUT_CART_AMP_ENV_SUSTAIN_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 4)
#define LAYOUT_CART_AMP_ENV_RATE_KS_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 5)
#define LAYOUT_CART_AMP_ENV_LEFT_KS_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 6)
#define LAYOUT_CART_AMP_ENV_RIGHT_KS_Y      LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 7)
#define LAYOUT_CART_AMP_ENV_BREAK_POINT_Y   LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 8)

#define LAYOUT_CART_HEADER_FILTER_ENV_X     LAYOUT_CART_COLUMN_2_CENTER_X
#define LAYOUT_CART_HEADER_FILTER_ENV_Y     LAYOUT_CART_HEADER_AMP_ENV_Y

#define LAYOUT_CART_FILTER_ENV_ATTACK_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 0)
#define LAYOUT_CART_FILTER_ENV_DECAY_1_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 1)
#define LAYOUT_CART_FILTER_ENV_DECAY_2_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 2)
#define LAYOUT_CART_FILTER_ENV_RELEASE_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 3)
#define LAYOUT_CART_FILTER_ENV_AMPLITUDE_Y  LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 4)
#define LAYOUT_CART_FILTER_ENV_SUSTAIN_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 5)
#define LAYOUT_CART_FILTER_ENV_HOLD_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 6)
#define LAYOUT_CART_FILTER_ENV_FINALE_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 7)
#define LAYOUT_CART_FILTER_ENV_RATE_KS_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_FILTER_ENV_Y, 8)

#define LAYOUT_CART_HEADER_EXTRA_ENV_X     LAYOUT_CART_COLUMN_3_CENTER_X
#define LAYOUT_CART_HEADER_EXTRA_ENV_Y     LAYOUT_CART_HEADER_AMP_ENV_Y

#define LAYOUT_CART_EXTRA_ENV_ATTACK_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 0)
#define LAYOUT_CART_EXTRA_ENV_DECAY_1_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 1)
#define LAYOUT_CART_EXTRA_ENV_DECAY_2_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 2)
#define LAYOUT_CART_EXTRA_ENV_RELEASE_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 3)
#define LAYOUT_CART_EXTRA_ENV_AMPLITUDE_Y  LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 4)
#define LAYOUT_CART_EXTRA_ENV_SUSTAIN_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 5)
#define LAYOUT_CART_EXTRA_ENV_HOLD_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 6)
#define LAYOUT_CART_EXTRA_ENV_FINALE_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 7)
#define LAYOUT_CART_EXTRA_ENV_RATE_KS_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EXTRA_ENV_Y, 8)

#define LAYOUT_CART_HEADER_PORTAMENTO_X   LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_HEADER_PORTAMENTO_Y   LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_AMP_ENV_Y, 8)

#define LAYOUT_CART_PORTAMENTO_MODE_Y     LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PORTAMENTO_Y, 0)
#define LAYOUT_CART_PORTAMENTO_FOLLOW_Y   LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PORTAMENTO_Y, 1)
#define LAYOUT_CART_PORTAMENTO_LEGATO_Y   LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PORTAMENTO_Y, 2)
#define LAYOUT_CART_PORTAMENTO_SPEED_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PORTAMENTO_Y, 3)

#define LAYOUT_CART_HEADER_ARPEGGIO_X     LAYOUT_CART_COLUMN_2_CENTER_X
#define LAYOUT_CART_HEADER_ARPEGGIO_Y     LAYOUT_CART_HEADER_PORTAMENTO_Y

#define LAYOUT_CART_ARPEGGIO_MODE_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_ARPEGGIO_Y, 0)
#define LAYOUT_CART_ARPEGGIO_PATTERN_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_ARPEGGIO_Y, 1)
#define LAYOUT_CART_ARPEGGIO_OCTAVES_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_ARPEGGIO_Y, 2)
#define LAYOUT_CART_ARPEGGIO_SPEED_Y      LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_ARPEGGIO_Y, 3)

#define LAYOUT_CART_HEADER_LFO_X          LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_HEADER_LFO_Y          LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_PORTAMENTO_Y, 3)

#define LAYOUT_CART_LFO_WAVEFORM_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LFO_Y, 0)
#define LAYOUT_CART_LFO_FREQUENCY_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LFO_Y, 1)
#define LAYOUT_CART_LFO_DELAY_Y           LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LFO_Y, 2)
#define LAYOUT_CART_LFO_QUANTIZE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_LFO_Y, 3)

#define LAYOUT_CART_HEADER_VIBRATO_X      LAYOUT_CART_COLUMN_2_CENTER_X
#define LAYOUT_CART_HEADER_VIBRATO_Y      LAYOUT_CART_HEADER_LFO_Y

#define LAYOUT_CART_VIBRATO_MODE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_VIBRATO_Y, 0)
#define LAYOUT_CART_VIBRATO_DEPTH_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_VIBRATO_Y, 1)
#define LAYOUT_CART_VIBRATO_BASE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_VIBRATO_Y, 2)

#define LAYOUT_CART_HEADER_TREMOLO_X      LAYOUT_CART_COLUMN_3_CENTER_X
#define LAYOUT_CART_HEADER_TREMOLO_Y      LAYOUT_CART_HEADER_LFO_Y

#define LAYOUT_CART_TREMOLO_MODE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_TREMOLO_Y, 0)
#define LAYOUT_CART_TREMOLO_DEPTH_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_TREMOLO_Y, 1)
#define LAYOUT_CART_TREMOLO_BASE_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_TREMOLO_Y, 2)

#define LAYOUT_CART_HEADER_EFFECTS_X      LAYOUT_CART_COLUMN_4_CENTER_X
#define LAYOUT_CART_HEADER_EFFECTS_Y      LAYOUT_CART_HEADER_LFO_Y

#define LAYOUT_CART_MOD_WHEEL_EFFECT_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EFFECTS_Y, 0)
#define LAYOUT_CART_AFTERTOUCH_EFFECT_Y   LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EFFECTS_Y, 1)
#define LAYOUT_CART_EXP_PEDAL_EFFECT_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_EFFECTS_Y, 2)

#define LAYOUT_CART_HEADER_PEDAL_X        LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_HEADER_PEDAL_Y        LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_LFO_Y, 3)

#define LAYOUT_CART_PEDAL_ADJUST_Y        LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PEDAL_Y, 0)

#define LAYOUT_CART_HEADER_VELOCITY_X     LAYOUT_CART_COLUMN_2_CENTER_X
#define LAYOUT_CART_HEADER_VELOCITY_Y     LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_VIBRATO_Y, 2)

#define LAYOUT_CART_VELOCITY_MODE_Y       LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_VELOCITY_Y, 0)
#define LAYOUT_CART_VELOCITY_SCALING_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_VELOCITY_Y, 1)

#define LAYOUT_CART_HEADER_SYNC_X         LAYOUT_CART_COLUMN_3_CENTER_X
#define LAYOUT_CART_HEADER_SYNC_Y         LAYOUT_CART_HEADER_VELOCITY_Y

#define LAYOUT_CART_SYNC_OSC_Y            LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_SYNC_Y, 0)
#define LAYOUT_CART_SYNC_LFO_Y            LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_SYNC_Y, 1)

#define LAYOUT_CART_HEADER_BOOST_X        LAYOUT_CART_COLUMN_4_CENTER_X
#define LAYOUT_CART_HEADER_BOOST_Y        LAYOUT_CART_HEADER_VELOCITY_Y

#define LAYOUT_CART_BOOST_MODE_Y          LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_BOOST_Y, 0)
#define LAYOUT_CART_BOOST_DEPTH_Y         LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_BOOST_Y, 1)

#define LAYOUT_CART_HEADER_PITCH_WHEEL_X  LAYOUT_CART_COLUMN_1_CENTER_X
#define LAYOUT_CART_HEADER_PITCH_WHEEL_Y  LAYOUT_CART_COMPUTE_NEXT_HEADER_Y(LAYOUT_CART_HEADER_PEDAL_Y, 0)

#define LAYOUT_CART_PITCH_WHEEL_MODE_Y    LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PITCH_WHEEL_Y, 0)
#define LAYOUT_CART_PITCH_WHEEL_RANGE_Y   LAYOUT_CART_COMPUTE_PARAM_Y(LAYOUT_CART_HEADER_PITCH_WHEEL_Y, 1)

/* audition panel parameters */
#define LAYOUT_CART_AUDITION_VELOCITY_Y     25
#define LAYOUT_CART_AUDITION_MOD_WHEEL_Y    25
#define LAYOUT_CART_AUDITION_AFTERTOUCH_Y   25
#define LAYOUT_CART_AUDITION_PITCH_WHEEL_Y  25

#define LAYOUT_CART_PARAM_NAME_X            -8

#define LAYOUT_CART_PARAM_SLIDER_VALUE_X    -2
#define LAYOUT_CART_PARAM_SLIDER_TRACK_X     6
#define LAYOUT_CART_PARAM_SLIDER_WIDTH       5

#define LAYOUT_CART_PARAM_ARROWS_LEFT_X     -2
#define LAYOUT_CART_PARAM_ARROWS_VALUE_X     4
#define LAYOUT_CART_PARAM_ARROWS_RIGHT_X    10

#define LAYOUT_CART_PARAM_RADIO_BUTTON_X    -2
#define LAYOUT_CART_PARAM_RADIO_VALUE_X      6

/* browser buttons, headers, and filenames */
#define LAYOUT_BROWSER_MAIN_HEADER_X    -1
#define LAYOUT_BROWSER_MAIN_HEADER_Y   -13

#define LAYOUT_BROWSER_DIR_PANEL_NAME_X  -44
#define LAYOUT_BROWSER_DIR_PANEL_NAME_Y   -9

#define LAYOUT_BROWSER_FILE_PANEL_NAME_X -44
#define LAYOUT_BROWSER_FILE_PANEL_NAME_Y  25

#define LAYOUT_BROWSER_LIST_NAME_X       -47
#define LAYOUT_BROWSER_LIST_NAME_START_Y  -5
#define LAYOUT_BROWSER_LIST_NAME_STEP_Y    3

typedef struct button
{
  int label;

  int center_x;
  int center_y;

  int width;
  int state;
} button;

typedef struct header
{
  int label;

  int center_x;
  int center_y;
} header;

typedef struct param
{
  int label;

  int type;

  int center_x;
  int center_y;

  short int lower_bound;
  short int upper_bound;
} param;

extern button G_layout_buttons[LAYOUT_NUM_BUTTONS];
extern header G_layout_headers[LAYOUT_NUM_HEADERS];
extern param  G_layout_params[LAYOUT_NUM_PARAMS];

/* function declarations */
short int layout_setup_all();

short int layout_reset_top_panel_button_states();
short int layout_reset_cart_button_states();

#endif
