/*******************************************************************************
** midicont.h (midi controllers)
*******************************************************************************/

#ifndef MIDI_CONT_H
#define MIDI_CONT_H

enum
{
  MIDI_CONT_PORTAMENTO_SWITCH_OFF = 0, 
  MIDI_CONT_PORTAMENTO_SWITCH_ON
};

enum
{
  MIDI_CONT_SUSTAIN_PEDAL_UP = 0, 
  MIDI_CONT_SUSTAIN_PEDAL_DOWN
};

enum
{
  MIDI_CONT_PEDAL_BEHAVIOR_STANDARD = 1, 
  MIDI_CONT_PEDAL_BEHAVIOR_INVERTED, 
  MIDI_CONT_PEDAL_BEHAVIOR_TOGGLE 
};

#define MIDI_CONT_MOD_WHEEL_DEFAULT       0
#define MIDI_CONT_MOD_WHEEL_LOWER_BOUND   0
#define MIDI_CONT_MOD_WHEEL_UPPER_BOUND   16
#define MIDI_CONT_MOD_WHEEL_NUM_VALUES    (MIDI_CONT_MOD_WHEEL_UPPER_BOUND - MIDI_CONT_MOD_WHEEL_LOWER_BOUND + 1)

#define MIDI_CONT_AFTERTOUCH_DEFAULT      0
#define MIDI_CONT_AFTERTOUCH_LOWER_BOUND  0
#define MIDI_CONT_AFTERTOUCH_UPPER_BOUND  16
#define MIDI_CONT_AFTERTOUCH_NUM_VALUES   (MIDI_CONT_AFTERTOUCH_UPPER_BOUND - MIDI_CONT_AFTERTOUCH_LOWER_BOUND + 1)

#define MIDI_CONT_PITCH_WHEEL_DEFAULT       0
#define MIDI_CONT_PITCH_WHEEL_LOWER_BOUND  -16
#define MIDI_CONT_PITCH_WHEEL_UPPER_BOUND   16
#define MIDI_CONT_PITCH_WHEEL_NUM_VALUES    (MIDI_CONT_PITCH_WHEEL_UPPER_BOUND - MIDI_CONT_PITCH_WHEEL_LOWER_BOUND + 1)

#define MIDI_CONT_PITCH_WHEEL_CENTER_VALUE  0

#define MIDI_CONT_PORTAMENTO_SWITCH_DEFAULT     MIDI_CONT_PORTAMENTO_SWITCH_OFF
#define MIDI_CONT_PORTAMENTO_SWITCH_LOWER_BOUND MIDI_CONT_PORTAMENTO_SWITCH_OFF
#define MIDI_CONT_PORTAMENTO_SWITCH_UPPER_BOUND MIDI_CONT_PORTAMENTO_SWITCH_ON
#define MIDI_CONT_PORTAMENTO_SWITCH_NUM_VALUES  (MIDI_CONT_PORTAMENTO_SWITCH_UPPER_BOUND - MIDI_CONT_PORTAMENTO_SWITCH_LOWER_BOUND + 1)

#define MIDI_CONT_SUSTAIN_PEDAL_DEFAULT         MIDI_CONT_SUSTAIN_PEDAL_UP
#define MIDI_CONT_SUSTAIN_PEDAL_LOWER_BOUND     MIDI_CONT_SUSTAIN_PEDAL_UP
#define MIDI_CONT_SUSTAIN_PEDAL_UPPER_BOUND     MIDI_CONT_SUSTAIN_PEDAL_DOWN
#define MIDI_CONT_SUSTAIN_PEDAL_NUM_VALUES      (MIDI_CONT_SUSTAIN_PEDAL_UPPER_BOUND - MIDI_CONT_SUSTAIN_PEDAL_LOWER_BOUND + 1)

#endif
