/*******************************************************************************
** midicont.h (midi controllers)
*******************************************************************************/

#ifndef MIDI_CONT_H
#define MIDI_CONT_H

enum
{
  MIDI_CONT_SWITCH_STATE_OFF = 0, 
  MIDI_CONT_SWITCH_STATE_ON
};

enum
{
  MIDI_CONT_PEDAL_STATE_UP = 0, 
  MIDI_CONT_PEDAL_STATE_DOWN
};

#define MIDI_CONT_NOTE_VELOCITY_DEFAULT     12
#define MIDI_CONT_NOTE_VELOCITY_LOWER_BOUND 0
#define MIDI_CONT_NOTE_VELOCITY_UPPER_BOUND 16
#define MIDI_CONT_NOTE_VELOCITY_NUM_VALUES  (MIDI_CONT_NOTE_VELOCITY_UPPER_BOUND - MIDI_CONT_NOTE_VELOCITY_LOWER_BOUND + 1)

#define MIDI_CONT_NOTE_VELOCITY_BREAK_POINT 12
#define MIDI_CONT_NOTE_VELOCITY_DIVISOR     12

#define MIDI_CONT_MOD_WHEEL_DEFAULT         0
#define MIDI_CONT_MOD_WHEEL_LOWER_BOUND     0
#define MIDI_CONT_MOD_WHEEL_UPPER_BOUND     16
#define MIDI_CONT_MOD_WHEEL_NUM_VALUES      (MIDI_CONT_MOD_WHEEL_UPPER_BOUND - MIDI_CONT_MOD_WHEEL_LOWER_BOUND + 1)

#define MIDI_CONT_AFTERTOUCH_DEFAULT        0
#define MIDI_CONT_AFTERTOUCH_LOWER_BOUND    0
#define MIDI_CONT_AFTERTOUCH_UPPER_BOUND    16
#define MIDI_CONT_AFTERTOUCH_NUM_VALUES     (MIDI_CONT_AFTERTOUCH_UPPER_BOUND - MIDI_CONT_AFTERTOUCH_LOWER_BOUND + 1)

#define MIDI_CONT_PITCH_WHEEL_DEFAULT       16
#define MIDI_CONT_PITCH_WHEEL_LOWER_BOUND   0
#define MIDI_CONT_PITCH_WHEEL_UPPER_BOUND   32
#define MIDI_CONT_PITCH_WHEEL_NUM_VALUES    (MIDI_CONT_PITCH_WHEEL_UPPER_BOUND - MIDI_CONT_PITCH_WHEEL_LOWER_BOUND + 1)

#define MIDI_CONT_PITCH_WHEEL_CENTER_VALUE  16
#define MIDI_CONT_PITCH_WHEEL_DIVISOR       16

#define MIDI_CONT_PORTAMENTO_SWITCH_DEFAULT     MIDI_CONT_SWITCH_STATE_OFF
#define MIDI_CONT_PORTAMENTO_SWITCH_LOWER_BOUND MIDI_CONT_SWITCH_STATE_OFF
#define MIDI_CONT_PORTAMENTO_SWITCH_UPPER_BOUND MIDI_CONT_SWITCH_STATE_ON
#define MIDI_CONT_PORTAMENTO_SWITCH_NUM_VALUES  (MIDI_CONT_PORTAMENTO_SWITCH_UPPER_BOUND - MIDI_CONT_PORTAMENTO_SWITCH_LOWER_BOUND + 1)

#define MIDI_CONT_ARPEGGIO_SWITCH_DEFAULT       MIDI_CONT_SWITCH_STATE_OFF
#define MIDI_CONT_ARPEGGIO_SWITCH_LOWER_BOUND   MIDI_CONT_SWITCH_STATE_OFF
#define MIDI_CONT_ARPEGGIO_SWITCH_UPPER_BOUND   MIDI_CONT_SWITCH_STATE_ON
#define MIDI_CONT_ARPEGGIO_SWITCH_NUM_VALUES    (MIDI_CONT_ARPEGGIO_SWITCH_UPPER_BOUND - MIDI_CONT_ARPEGGIO_SWITCH_LOWER_BOUND + 1)

#define MIDI_CONT_SUSTAIN_PEDAL_DEFAULT     MIDI_CONT_PEDAL_STATE_UP
#define MIDI_CONT_SUSTAIN_PEDAL_LOWER_BOUND MIDI_CONT_PEDAL_STATE_UP
#define MIDI_CONT_SUSTAIN_PEDAL_UPPER_BOUND MIDI_CONT_PEDAL_STATE_DOWN
#define MIDI_CONT_SUSTAIN_PEDAL_NUM_VALUES  (MIDI_CONT_SUSTAIN_PEDAL_UPPER_BOUND - MIDI_CONT_SUSTAIN_PEDAL_LOWER_BOUND + 1)

#endif
