/*******************************************************************************
** patch.h (patch settings)
*******************************************************************************/

#ifndef PATCH_H
#define PATCH_H

#include "bank.h"

enum
{
  PATCH_PROGRAM_WAVE_MIX = 1, 
  PATCH_PROGRAM_SYNC, 
  PATCH_PROGRAM_RING_MOD, 
  PATCH_PROGRAM_PULSE, 
  PATCH_PROGRAM_LAZY_SQUARE, 
  PATCH_PROGRAM_OVERDRIVE, 
  PATCH_PROGRAM_PHASE_DISTORT, 
  PATCH_PROGRAM_FREQ_MOD 
};

enum
{
  PATCH_OSC_WAVEFORM_TRIANGLE = 1, 
  PATCH_OSC_WAVEFORM_SQUARE, 
  PATCH_OSC_WAVEFORM_SAW 
};

enum
{
  PATCH_FM_WAVEFORM_SINE = 1, 
  PATCH_FM_WAVEFORM_HALF, 
  PATCH_FM_WAVEFORM_FULL, 
  PATCH_FM_WAVEFORM_QUARTER, 
  PATCH_FM_WAVEFORM_ALTERNATING, 
  PATCH_FM_WAVEFORM_CAMEL, 
  PATCH_FM_WAVEFORM_SQUARE, 
  PATCH_FM_WAVEFORM_LOG_SAW 
};

enum
{
  PATCH_PORTAMENTO_MODE_BEND = 1, 
  PATCH_PORTAMENTO_MODE_SEMITONES 
};

enum
{
  PATCH_PORTAMENTO_FOLLOW_CONTINUE = 0, 
  PATCH_PORTAMENTO_FOLLOW_RETURN 
};

enum
{
  PATCH_PORTAMENTO_LEGATO_OFF = 0, 
  PATCH_PORTAMENTO_LEGATO_ON 
};

enum
{
  PATCH_ARPEGGIO_MODE_HARP = 1, 
  PATCH_ARPEGGIO_MODE_ROLLED 
};

enum
{
  PATCH_ARPEGGIO_PATTERN_UP = 0, 
  PATCH_ARPEGGIO_PATTERN_DOWN, 
  PATCH_ARPEGGIO_PATTERN_UP_AND_DOWN, 
  PATCH_ARPEGGIO_PATTERN_UP_AND_DOWN_ALT 
};

enum
{
  PATCH_LFO_WAVEFORM_TRIANGLE = 1, 
  PATCH_LFO_WAVEFORM_SQUARE, 
  PATCH_LFO_WAVEFORM_SAW_UP, 
  PATCH_LFO_WAVEFORM_SAW_DOWN, 
  PATCH_LFO_WAVEFORM_NOISE_SQUARE, 
  PATCH_LFO_WAVEFORM_NOISE_SAW 
};

enum
{
  PATCH_VIBRATO_MODE_UP_AND_DOWN = 1, 
  PATCH_VIBRATO_MODE_UP_ONLY
};

enum
{
  PATCH_TREMOLO_MODE_CARRIERS = 1, 
  PATCH_TREMOLO_MODE_MODULATORS
};

enum
{
  PATCH_CONTROLLER_EFFECT_VIBRATO = 1, 
  PATCH_CONTROLLER_EFFECT_TREMOLO, 
  PATCH_CONTROLLER_EFFECT_BOOST, 
  PATCH_CONTROLLER_EFFECT_VIB_PLUS_TREM, 
  PATCH_CONTROLLER_EFFECT_VIB_PLUS_BOOST, 
  PATCH_CONTROLLER_EFFECT_TREM_PLUS_BOOST, 
  PATCH_CONTROLLER_EFFECT_ALL_THREE 
};

enum
{
  PATCH_VELOCITY_MODE_CARRIERS = 1, 
  PATCH_VELOCITY_MODE_MODULATORS
};

enum
{
  PATCH_SYNC_OFF = 0, 
  PATCH_SYNC_ON 
};

enum
{
  PATCH_BOOST_MODE_CARRIERS = 1, 
  PATCH_BOOST_MODE_MODULATORS
};

enum
{
  PATCH_PITCH_WHEEL_MODE_BEND = 1, 
  PATCH_PITCH_WHEEL_MODE_SEMITONES 
};

enum
{
  PATCH_HIGHPASS_CUTOFF_A0 = 1, 
  PATCH_HIGHPASS_CUTOFF_A1,
  PATCH_HIGHPASS_CUTOFF_A2,
  PATCH_HIGHPASS_CUTOFF_A3
};

#if 0
enum
{
  PATCH_LOWPASS_CUTOFF_E7 = 1, 
  PATCH_LOWPASS_CUTOFF_G7,
  PATCH_LOWPASS_CUTOFF_A7,
  PATCH_LOWPASS_CUTOFF_C8
};
#endif

/* cart parameters */
#define PATCH_CART_NO_DEFAULT     1
#define PATCH_CART_NO_LOWER_BOUND 1
#define PATCH_CART_NO_UPPER_BOUND BANK_NUM_CARTS
#define PATCH_CART_NO_NUM_VALUES  (PATCH_CART_NO_UPPER_BOUND - PATCH_CART_NO_LOWER_BOUND + 1)

#define PATCH_CART_NO_IS_VALID(num)                                            \
  ((num >= PATCH_CART_NO_LOWER_BOUND) && (num <= PATCH_CART_NO_UPPER_BOUND))

#define PATCH_CART_NO_IS_NOT_VALID(num)                                        \
  (!(PATCH_CART_NO_IS_VALID(num)))

#define PATCH_PATCH_NO_DEFAULT      1
#define PATCH_PATCH_NO_LOWER_BOUND  1
#define PATCH_PATCH_NO_UPPER_BOUND  BANK_PATCHES_PER_CART
#define PATCH_PATCH_NO_NUM_VALUES   (PATCH_PATCH_NO_UPPER_BOUND - PATCH_PATCH_NO_LOWER_BOUND + 1)

#define PATCH_PATCH_NO_IS_VALID(num)                                           \
  ((num >= PATCH_PATCH_NO_LOWER_BOUND) && (num <= PATCH_PATCH_NO_UPPER_BOUND))

#define PATCH_PATCH_NO_IS_NOT_VALID(num)                                       \
  (!(PATCH_PATCH_NO_IS_VALID(num)))

#define PATCH_COMPUTE_CART_INDEX(cart_num)                                     \
  cart_index = cart_num - PATCH_CART_NO_LOWER_BOUND;

#define PATCH_COMPUTE_PATCH_INDEX(cart_num, patch_num)                         \
  patch_index = ((cart_num - PATCH_CART_NO_LOWER_BOUND) * BANK_PATCHES_PER_CART) + (patch_num - PATCH_PATCH_NO_LOWER_BOUND);

/* name strings: x characters + 1 null terminator */
#define PATCH_CART_NAME_SIZE  (8 + 1)
#define PATCH_PATCH_NAME_SIZE (10 + 1)

/* patch parameters */

/* program */
#define PATCH_PROGRAM_DEFAULT     PATCH_PROGRAM_WAVE_MIX
#define PATCH_PROGRAM_LOWER_BOUND PATCH_PROGRAM_WAVE_MIX
#define PATCH_PROGRAM_UPPER_BOUND PATCH_PROGRAM_FREQ_MOD
#define PATCH_PROGRAM_NUM_VALUES  (PATCH_PROGRAM_UPPER_BOUND - PATCH_PROGRAM_LOWER_BOUND + 1)

/* oscillators */
#define PATCH_OSC_WAVEFORM_DEFAULT      PATCH_OSC_WAVEFORM_TRIANGLE
#define PATCH_OSC_WAVEFORM_LOWER_BOUND  PATCH_OSC_WAVEFORM_TRIANGLE
#define PATCH_OSC_WAVEFORM_UPPER_BOUND  PATCH_OSC_WAVEFORM_SAW
#define PATCH_OSC_WAVEFORM_NUM_VALUES   (PATCH_OSC_WAVEFORM_UPPER_BOUND - PATCH_OSC_WAVEFORM_LOWER_BOUND + 1)

#define PATCH_FM_WAVEFORM_DEFAULT       PATCH_FM_WAVEFORM_SINE
#define PATCH_FM_WAVEFORM_LOWER_BOUND   PATCH_FM_WAVEFORM_SINE
#define PATCH_FM_WAVEFORM_UPPER_BOUND   PATCH_FM_WAVEFORM_LOG_SAW
#define PATCH_FM_WAVEFORM_NUM_VALUES    (PATCH_FM_WAVEFORM_UPPER_BOUND - PATCH_FM_WAVEFORM_LOWER_BOUND + 1)

#define PATCH_FM_FEEDBACK_DEFAULT       0
#define PATCH_FM_FEEDBACK_LOWER_BOUND   0
#define PATCH_FM_FEEDBACK_UPPER_BOUND   7
#define PATCH_FM_FEEDBACK_NUM_VALUES    (PATCH_FM_FEEDBACK_UPPER_BOUND - PATCH_FM_FEEDBACK_LOWER_BOUND + 1)

#define PATCH_OSC_MULTIPLE_DEFAULT      1
#define PATCH_OSC_MULTIPLE_LOWER_BOUND  1
#define PATCH_OSC_MULTIPLE_UPPER_BOUND  16
#define PATCH_OSC_MULTIPLE_NUM_VALUES   (PATCH_OSC_MULTIPLE_UPPER_BOUND - PATCH_OSC_MULTIPLE_LOWER_BOUND + 1)

#define PATCH_OSC_DIVISOR_DEFAULT       1
#define PATCH_OSC_DIVISOR_LOWER_BOUND   1
#define PATCH_OSC_DIVISOR_UPPER_BOUND   8
#define PATCH_OSC_DIVISOR_NUM_VALUES    (PATCH_OSC_DIVISOR_UPPER_BOUND - PATCH_OSC_DIVISOR_LOWER_BOUND + 1)

#define PATCH_OSC_DETUNE_DEFAULT        0
#define PATCH_OSC_DETUNE_LOWER_BOUND   -50
#define PATCH_OSC_DETUNE_UPPER_BOUND    50
#define PATCH_OSC_DETUNE_NUM_VALUES     (PATCH_OSC_DETUNE_UPPER_BOUND - PATCH_OSC_DETUNE_LOWER_BOUND + 1)

/* lowpass filter */
#define PATCH_LOWPASS_MULTIPLE_DEFAULT      1
#define PATCH_LOWPASS_MULTIPLE_LOWER_BOUND  1
#define PATCH_LOWPASS_MULTIPLE_UPPER_BOUND  16
#define PATCH_LOWPASS_MULTIPLE_NUM_VALUES   (PATCH_LOWPASS_MULTIPLE_UPPER_BOUND - PATCH_LOWPASS_MULTIPLE_LOWER_BOUND + 1)

#define PATCH_LOWPASS_DIVISOR_DEFAULT       1
#define PATCH_LOWPASS_DIVISOR_LOWER_BOUND   1
#define PATCH_LOWPASS_DIVISOR_UPPER_BOUND   8
#define PATCH_LOWPASS_DIVISOR_NUM_VALUES    (PATCH_LOWPASS_DIVISOR_UPPER_BOUND - PATCH_LOWPASS_DIVISOR_LOWER_BOUND + 1)

#define PATCH_LOWPASS_KEYTRACKING_DEFAULT       0
#define PATCH_LOWPASS_KEYTRACKING_LOWER_BOUND   0
#define PATCH_LOWPASS_KEYTRACKING_UPPER_BOUND   8
#define PATCH_LOWPASS_KEYTRACKING_NUM_VALUES    (PATCH_LOWPASS_KEYTRACKING_UPPER_BOUND - PATCH_LOWPASS_KEYTRACKING_LOWER_BOUND + 1)

/* highpass filter */
#define PATCH_HIGHPASS_CUTOFF_DEFAULT     PATCH_HIGHPASS_CUTOFF_A0
#define PATCH_HIGHPASS_CUTOFF_LOWER_BOUND PATCH_HIGHPASS_CUTOFF_A0
#define PATCH_HIGHPASS_CUTOFF_UPPER_BOUND PATCH_HIGHPASS_CUTOFF_A3
#define PATCH_HIGHPASS_CUTOFF_NUM_VALUES  (PATCH_HIGHPASS_CUTOFF_UPPER_BOUND - PATCH_HIGHPASS_CUTOFF_LOWER_BOUND + 1)

/* amplitude envelopes */
#define PATCH_ENV_TIME_DEFAULT      1
#define PATCH_ENV_TIME_LOWER_BOUND  1
#define PATCH_ENV_TIME_UPPER_BOUND  100
#define PATCH_ENV_TIME_NUM_VALUES   (PATCH_ENV_TIME_UPPER_BOUND - PATCH_ENV_TIME_LOWER_BOUND + 1)

#define PATCH_ENV_LEVEL_DEFAULT     0
#define PATCH_ENV_LEVEL_LOWER_BOUND 0
#define PATCH_ENV_LEVEL_UPPER_BOUND 100
#define PATCH_ENV_LEVEL_NUM_VALUES  (PATCH_ENV_LEVEL_UPPER_BOUND - PATCH_ENV_LEVEL_LOWER_BOUND + 1)

#define PATCH_ENV_KEYSCALING_DEFAULT      2
#define PATCH_ENV_KEYSCALING_LOWER_BOUND  0
#define PATCH_ENV_KEYSCALING_UPPER_BOUND  8
#define PATCH_ENV_KEYSCALING_NUM_VALUES   (PATCH_ENV_KEYSCALING_UPPER_BOUND - PATCH_ENV_KEYSCALING_LOWER_BOUND + 1)

#define PATCH_ENV_BREAK_POINT_DEFAULT     5
#define PATCH_ENV_BREAK_POINT_LOWER_BOUND 1
#define PATCH_ENV_BREAK_POINT_UPPER_BOUND 16
#define PATCH_ENV_BREAK_POINT_NUM_VALUES  (PATCH_ENV_BREAK_POINT_UPPER_BOUND - PATCH_ENV_BREAK_POINT_LOWER_BOUND + 1)

/* pitch envelopes */
#define PATCH_PEG_TIME_DEFAULT      1
#define PATCH_PEG_TIME_LOWER_BOUND  1
#define PATCH_PEG_TIME_UPPER_BOUND  100
#define PATCH_PEG_TIME_NUM_VALUES   (PATCH_PEG_TIME_UPPER_BOUND - PATCH_PEG_TIME_LOWER_BOUND + 1)

#define PATCH_PEG_LEVEL_DEFAULT     0
#define PATCH_PEG_LEVEL_LOWER_BOUND -48
#define PATCH_PEG_LEVEL_UPPER_BOUND 48
#define PATCH_PEG_LEVEL_NUM_VALUES  (PATCH_PEG_LEVEL_UPPER_BOUND - PATCH_PEG_LEVEL_LOWER_BOUND + 1)

#define PATCH_PEG_KEYSCALING_DEFAULT      2
#define PATCH_PEG_KEYSCALING_LOWER_BOUND  0
#define PATCH_PEG_KEYSCALING_UPPER_BOUND  8
#define PATCH_PEG_KEYSCALING_NUM_VALUES   (PATCH_PEG_KEYSCALING_UPPER_BOUND - PATCH_PEG_KEYSCALING_LOWER_BOUND + 1)

/* portamento */
#define PATCH_PORTAMENTO_MODE_DEFAULT         PATCH_PORTAMENTO_MODE_BEND
#define PATCH_PORTAMENTO_MODE_LOWER_BOUND     PATCH_PORTAMENTO_MODE_BEND
#define PATCH_PORTAMENTO_MODE_UPPER_BOUND     PATCH_PORTAMENTO_MODE_SEMITONES
#define PATCH_PORTAMENTO_MODE_NUM_VALUES      (PATCH_PORTAMENTO_MODE_UPPER_BOUND - PATCH_PORTAMENTO_MODE_LOWER_BOUND + 1)

#define PATCH_PORTAMENTO_FOLLOW_DEFAULT       PATCH_PORTAMENTO_FOLLOW_CONTINUE
#define PATCH_PORTAMENTO_FOLLOW_LOWER_BOUND   PATCH_PORTAMENTO_FOLLOW_CONTINUE
#define PATCH_PORTAMENTO_FOLLOW_UPPER_BOUND   PATCH_PORTAMENTO_FOLLOW_RETURN
#define PATCH_PORTAMENTO_FOLLOW_NUM_VALUES    (PATCH_PORTAMENTO_FOLLOW_UPPER_BOUND - PATCH_PORTAMENTO_FOLLOW_LOWER_BOUND + 1)

#define PATCH_PORTAMENTO_LEGATO_DEFAULT       PATCH_PORTAMENTO_LEGATO_OFF
#define PATCH_PORTAMENTO_LEGATO_LOWER_BOUND   PATCH_PORTAMENTO_LEGATO_OFF
#define PATCH_PORTAMENTO_LEGATO_UPPER_BOUND   PATCH_PORTAMENTO_LEGATO_ON
#define PATCH_PORTAMENTO_LEGATO_NUM_VALUES    (PATCH_PORTAMENTO_LEGATO_UPPER_BOUND - PATCH_PORTAMENTO_LEGATO_LOWER_BOUND + 1)

#define PATCH_PORTAMENTO_SPEED_DEFAULT        8
#define PATCH_PORTAMENTO_SPEED_LOWER_BOUND    1
#define PATCH_PORTAMENTO_SPEED_UPPER_BOUND    16
#define PATCH_PORTAMENTO_SPEED_NUM_VALUES     (PATCH_PORTAMENTO_SPEED_UPPER_BOUND - PATCH_PORTAMENTO_SPEED_LOWER_BOUND + 1)

/* arpeggio */
#define PATCH_ARPEGGIO_MODE_DEFAULT         PATCH_ARPEGGIO_MODE_HARP
#define PATCH_ARPEGGIO_MODE_LOWER_BOUND     PATCH_ARPEGGIO_MODE_HARP
#define PATCH_ARPEGGIO_MODE_UPPER_BOUND     PATCH_ARPEGGIO_MODE_ROLLED
#define PATCH_ARPEGGIO_MODE_NUM_VALUES      (PATCH_ARPEGGIO_MODE_UPPER_BOUND - PATCH_ARPEGGIO_MODE_LOWER_BOUND + 1)

#define PATCH_ARPEGGIO_PATTERN_DEFAULT      PATCH_ARPEGGIO_PATTERN_UP
#define PATCH_ARPEGGIO_PATTERN_LOWER_BOUND  PATCH_ARPEGGIO_PATTERN_UP
#define PATCH_ARPEGGIO_PATTERN_UPPER_BOUND  PATCH_ARPEGGIO_PATTERN_UP_AND_DOWN_ALT
#define PATCH_ARPEGGIO_PATTERN_NUM_VALUES   (PATCH_ARPEGGIO_PATTERN_UPPER_BOUND - PATCH_ARPEGGIO_PATTERN_LOWER_BOUND + 1)

#define PATCH_ARPEGGIO_OCTAVES_DEFAULT      1
#define PATCH_ARPEGGIO_OCTAVES_LOWER_BOUND  1
#define PATCH_ARPEGGIO_OCTAVES_UPPER_BOUND  4
#define PATCH_ARPEGGIO_OCTAVES_NUM_VALUES   (PATCH_ARPEGGIO_OCTAVES_UPPER_BOUND - PATCH_ARPEGGIO_OCTAVES_LOWER_BOUND + 1)

#define PATCH_ARPEGGIO_SPEED_DEFAULT        1
#define PATCH_ARPEGGIO_SPEED_LOWER_BOUND    1
#define PATCH_ARPEGGIO_SPEED_UPPER_BOUND    12
#define PATCH_ARPEGGIO_SPEED_NUM_VALUES     (PATCH_ARPEGGIO_SPEED_UPPER_BOUND - PATCH_ARPEGGIO_SPEED_LOWER_BOUND + 1)

/* lfo */
#define PATCH_LFO_WAVEFORM_DEFAULT      PATCH_LFO_WAVEFORM_TRIANGLE
#define PATCH_LFO_WAVEFORM_LOWER_BOUND  PATCH_LFO_WAVEFORM_TRIANGLE
#define PATCH_LFO_WAVEFORM_UPPER_BOUND  PATCH_LFO_WAVEFORM_NOISE_SAW
#define PATCH_LFO_WAVEFORM_NUM_VALUES   (PATCH_LFO_WAVEFORM_UPPER_BOUND - PATCH_LFO_WAVEFORM_LOWER_BOUND + 1)

#define PATCH_LFO_DELAY_DEFAULT         0
#define PATCH_LFO_DELAY_LOWER_BOUND     0
#define PATCH_LFO_DELAY_UPPER_BOUND     24
#define PATCH_LFO_DELAY_NUM_VALUES      (PATCH_LFO_DELAY_UPPER_BOUND - PATCH_LFO_DELAY_LOWER_BOUND + 1)

#define PATCH_LFO_FREQUENCY_DEFAULT     16
#define PATCH_LFO_FREQUENCY_LOWER_BOUND 1
#define PATCH_LFO_FREQUENCY_UPPER_BOUND 32
#define PATCH_LFO_FREQUENCY_NUM_VALUES  (PATCH_LFO_FREQUENCY_UPPER_BOUND - PATCH_LFO_FREQUENCY_LOWER_BOUND + 1)

#define PATCH_LFO_QUANTIZE_DEFAULT      32
#define PATCH_LFO_QUANTIZE_LOWER_BOUND  1
#define PATCH_LFO_QUANTIZE_UPPER_BOUND  32
#define PATCH_LFO_QUANTIZE_NUM_VALUES   (PATCH_LFO_QUANTIZE_UPPER_BOUND - PATCH_LFO_QUANTIZE_LOWER_BOUND + 1)

/* vibrato */
#define PATCH_VIBRATO_MODE_DEFAULT      PATCH_VIBRATO_MODE_UP_AND_DOWN
#define PATCH_VIBRATO_MODE_LOWER_BOUND  PATCH_VIBRATO_MODE_UP_AND_DOWN
#define PATCH_VIBRATO_MODE_UPPER_BOUND  PATCH_VIBRATO_MODE_UP_ONLY
#define PATCH_VIBRATO_MODE_NUM_VALUES   (PATCH_VIBRATO_MODE_UPPER_BOUND - PATCH_VIBRATO_MODE_LOWER_BOUND + 1)

/* tremolo */
#define PATCH_TREMOLO_MODE_DEFAULT      PATCH_TREMOLO_MODE_CARRIERS
#define PATCH_TREMOLO_MODE_LOWER_BOUND  PATCH_TREMOLO_MODE_CARRIERS
#define PATCH_TREMOLO_MODE_UPPER_BOUND  PATCH_TREMOLO_MODE_MODULATORS
#define PATCH_TREMOLO_MODE_NUM_VALUES   (PATCH_TREMOLO_MODE_UPPER_BOUND - PATCH_TREMOLO_MODE_LOWER_BOUND + 1)

/* effects */
#define PATCH_CONTROLLER_EFFECT_DEFAULT     PATCH_CONTROLLER_EFFECT_VIBRATO
#define PATCH_CONTROLLER_EFFECT_LOWER_BOUND PATCH_CONTROLLER_EFFECT_VIBRATO
#define PATCH_CONTROLLER_EFFECT_UPPER_BOUND PATCH_CONTROLLER_EFFECT_ALL_THREE
#define PATCH_CONTROLLER_EFFECT_NUM_VALUES  (PATCH_CONTROLLER_EFFECT_UPPER_BOUND - PATCH_CONTROLLER_EFFECT_LOWER_BOUND + 1)

/* sustain pedal */
#define PATCH_PEDAL_ADJUST_DEFAULT      4
#define PATCH_PEDAL_ADJUST_LOWER_BOUND  0
#define PATCH_PEDAL_ADJUST_UPPER_BOUND  8
#define PATCH_PEDAL_ADJUST_NUM_VALUES   (PATCH_PEDAL_ADJUST_UPPER_BOUND - PATCH_PEDAL_ADJUST_LOWER_BOUND + 1)

/* velocity */
#define PATCH_VELOCITY_MODE_DEFAULT         PATCH_VELOCITY_MODE_CARRIERS
#define PATCH_VELOCITY_MODE_LOWER_BOUND     PATCH_VELOCITY_MODE_CARRIERS
#define PATCH_VELOCITY_MODE_UPPER_BOUND     PATCH_VELOCITY_MODE_MODULATORS
#define PATCH_VELOCITY_MODE_NUM_VALUES      (PATCH_VELOCITY_MODE_UPPER_BOUND - PATCH_VELOCITY_MODE_LOWER_BOUND + 1)

#define PATCH_VELOCITY_SCALING_DEFAULT      4
#define PATCH_VELOCITY_SCALING_LOWER_BOUND  0
#define PATCH_VELOCITY_SCALING_UPPER_BOUND  8
#define PATCH_VELOCITY_SCALING_NUM_VALUES   (PATCH_VELOCITY_SCALING_UPPER_BOUND - PATCH_VELOCITY_SCALING_LOWER_BOUND + 1)

/* sync */
#define PATCH_SYNC_OSC_DEFAULT          PATCH_SYNC_ON
#define PATCH_SYNC_OSC_LOWER_BOUND      PATCH_SYNC_OFF
#define PATCH_SYNC_OSC_UPPER_BOUND      PATCH_SYNC_ON
#define PATCH_SYNC_OSC_NUM_VALUES       (PATCH_SYNC_OSC_UPPER_BOUND - PATCH_SYNC_OSC_LOWER_BOUND + 1)

#define PATCH_SYNC_LFO_DEFAULT          PATCH_SYNC_ON
#define PATCH_SYNC_LFO_LOWER_BOUND      PATCH_SYNC_OFF
#define PATCH_SYNC_LFO_UPPER_BOUND      PATCH_SYNC_ON
#define PATCH_SYNC_LFO_NUM_VALUES       (PATCH_SYNC_LFO_UPPER_BOUND - PATCH_SYNC_LFO_LOWER_BOUND + 1)

/* boost */
#define PATCH_BOOST_MODE_DEFAULT        PATCH_BOOST_MODE_CARRIERS
#define PATCH_BOOST_MODE_LOWER_BOUND    PATCH_BOOST_MODE_CARRIERS
#define PATCH_BOOST_MODE_UPPER_BOUND    PATCH_BOOST_MODE_MODULATORS
#define PATCH_BOOST_MODE_NUM_VALUES     (PATCH_BOOST_MODE_UPPER_BOUND - PATCH_BOOST_MODE_LOWER_BOUND + 1)

/* additional vibrato, tremolo, boost settings */
#define PATCH_EFFECT_DEPTH_DEFAULT      1
#define PATCH_EFFECT_DEPTH_LOWER_BOUND  1
#define PATCH_EFFECT_DEPTH_UPPER_BOUND  16
#define PATCH_EFFECT_DEPTH_NUM_VALUES   (PATCH_EFFECT_DEPTH_UPPER_BOUND - PATCH_EFFECT_DEPTH_LOWER_BOUND + 1)

#define PATCH_EFFECT_BASE_DEFAULT       0
#define PATCH_EFFECT_BASE_LOWER_BOUND   0
#define PATCH_EFFECT_BASE_UPPER_BOUND   16
#define PATCH_EFFECT_BASE_NUM_VALUES    (PATCH_EFFECT_BASE_UPPER_BOUND - PATCH_EFFECT_BASE_LOWER_BOUND + 1)

/* pitch wheel */
#define PATCH_PITCH_WHEEL_MODE_DEFAULT        PATCH_PITCH_WHEEL_MODE_BEND
#define PATCH_PITCH_WHEEL_MODE_LOWER_BOUND    PATCH_PITCH_WHEEL_MODE_BEND
#define PATCH_PITCH_WHEEL_MODE_UPPER_BOUND    PATCH_PITCH_WHEEL_MODE_SEMITONES
#define PATCH_PITCH_WHEEL_MODE_NUM_VALUES     (PATCH_PITCH_WHEEL_MODE_UPPER_BOUND - PATCH_PITCH_WHEEL_MODE_LOWER_BOUND + 1)

#define PATCH_PITCH_WHEEL_RANGE_DEFAULT       1
#define PATCH_PITCH_WHEEL_RANGE_LOWER_BOUND   1
#define PATCH_PITCH_WHEEL_RANGE_UPPER_BOUND   12
#define PATCH_PITCH_WHEEL_RANGE_NUM_VALUES    (PATCH_PITCH_WHEEL_RANGE_UPPER_BOUND - PATCH_PITCH_WHEEL_RANGE_LOWER_BOUND + 1)

/* sync */
#define PATCH_SYNC_DEFAULT      PATCH_SYNC_ON
#define PATCH_SYNC_LOWER_BOUND  PATCH_SYNC_OFF
#define PATCH_SYNC_UPPER_BOUND  PATCH_SYNC_ON
#define PATCH_SYNC_NUM_VALUES   (PATCH_SYNC_UPPER_BOUND - PATCH_SYNC_LOWER_BOUND + 1)

typedef struct patch
{
  /* program */
  short int program;

  /* oscillators */
  short int osc_1_waveform;
  short int osc_1_detune;

  short int osc_2_waveform;
  short int osc_2_detune;
  short int osc_2_multiple;
  short int osc_2_divisor;

  /* lowpass filter */
  short int lowpass_multiple;
  short int lowpass_divisor;
  short int lowpass_keytracking;

  /* highpass filter */
  short int highpass_cutoff;

  /* amplitude envelope */
  short int amp_env_attack;
  short int amp_env_decay_1;
  short int amp_env_decay_2;
  short int amp_env_release;
  short int amp_env_sustain;
  short int amp_env_rate_ks;
  short int amp_env_left_ks;
  short int amp_env_right_ks;
  short int amp_env_break_point;

  /* filter envelope */
  short int filt_peg_attack;
  short int filt_peg_decay_1;
  short int filt_peg_decay_2;
  short int filt_peg_release;
  short int filt_peg_amplitude;
  short int filt_peg_sustain;
  short int filt_peg_hold;
  short int filt_peg_finale;
  short int filt_peg_rate_ks;

  /* extra envelope */
  short int ex_peg_attack;
  short int ex_peg_decay_1;
  short int ex_peg_decay_2;
  short int ex_peg_release;
  short int ex_peg_amplitude;
  short int ex_peg_sustain;
  short int ex_peg_hold;
  short int ex_peg_finale;
  short int ex_peg_rate_ks;

  /* portamento */
  short int portamento_mode;
  short int portamento_follow;
  short int portamento_legato;
  short int portamento_speed;

  /* arpeggio */
  short int arpeggio_mode;
  short int arpeggio_pattern;
  short int arpeggio_octaves;
  short int arpeggio_speed;

  /* lfo */
  short int lfo_waveform;
  short int lfo_delay;
  short int lfo_frequency;
  short int lfo_quantize;

  /* vibrato */
  short int vibrato_mode;
  short int vibrato_depth;
  short int vibrato_base;

  /* tremolo */
  short int tremolo_mode;
  short int tremolo_depth;
  short int tremolo_base;

  /* effects */
  short int mod_wheel_effect;
  short int aftertouch_effect;
  short int exp_pedal_effect;

  /* sustain pedal */
  short int pedal_adjust;

  /* velocity */
  short int velocity_mode;
  short int velocity_scaling;

  /* sync */
  short int sync_osc;
  short int sync_lfo;

  /* boost */
  short int boost_mode;
  short int boost_depth;

  /* pitch wheel */
  short int pitch_wheel_mode;
  short int pitch_wheel_range;
} patch;

/* name & patch banks */
extern char   G_cart_names[BANK_NUM_CARTS][PATCH_CART_NAME_SIZE];
extern char   G_patch_names[BANK_NUM_PATCHES][PATCH_PATCH_NAME_SIZE];

extern patch  G_patch_bank[BANK_NUM_PATCHES];

/* function declarations */
short int patch_reset_all();

short int patch_reset_patch(int patch_index);
short int patch_validate_patch(int patch_index);
short int patch_copy_patch(int dest_patch_index, int src_patch_index);

short int patch_reset_cart(int cart_index);
short int patch_validate_cart(int cart_index);
short int patch_copy_cart(int dest_cart_index, int src_cart_index);

#endif
