/*******************************************************************************
** wheel.h (midi controllers)
*******************************************************************************/

#ifndef WHEEL_H
#define WHEEL_H

#define WHEEL_MOD_WHEEL_LOWER_BOUND 0
#define WHEEL_MOD_WHEEL_UPPER_BOUND 16
#define WHEEL_MOD_WHEEL_NUM_STEPS   (WHEEL_MOD_WHEEL_UPPER_BOUND - WHEEL_MOD_WHEEL_LOWER_BOUND + 1)

#define WHEEL_AFTERTOUCH_LOWER_BOUND  0
#define WHEEL_AFTERTOUCH_UPPER_BOUND  16
#define WHEEL_AFTERTOUCH_NUM_STEPS    (WHEEL_AFTERTOUCH_UPPER_BOUND - WHEEL_AFTERTOUCH_LOWER_BOUND + 1)

#define WHEEL_PITCH_WHEEL_LOWER_BOUND  -16
#define WHEEL_PITCH_WHEEL_UPPER_BOUND   16
#define WHEEL_PITCH_WHEEL_NUM_STEPS     (WHEEL_PITCH_WHEEL_UPPER_BOUND - WHEEL_PITCH_WHEEL_LOWER_BOUND + 1)

#define WHEEL_PITCH_WHEEL_CENTER_VALUE  ((WHEEL_PITCH_WHEEL_UPPER_BOUND + WHEEL_PITCH_WHEEL_LOWER_BOUND) / 2)

#endif
